<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chương 14 Tính toán phí bảo hiểm thuần bằng mô hình tần suất - mức độ nghiêm trọng. | Khoa Học Dữ Liệu trong Kinh tế và Kinh doanh</title>
<meta name="author" content="Nguyễn Quang Huy">
<meta name="description" content="Tính toán phí của các sản phẩm bảo hiểm là một công việc phức tạp đòi hỏi phải kết hợp nhiều yếu tố khác nhau. Trước hết dữ liệu lịch sử phải được phân tích chính xác, các xu hướng kinh tế xã hội...">
<meta name="generator" content="bookdown 0.37 with bs4_book()">
<meta property="og:title" content="Chương 14 Tính toán phí bảo hiểm thuần bằng mô hình tần suất - mức độ nghiêm trọng. | Khoa Học Dữ Liệu trong Kinh tế và Kinh doanh">
<meta property="og:type" content="book">
<meta property="og:description" content="Tính toán phí của các sản phẩm bảo hiểm là một công việc phức tạp đòi hỏi phải kết hợp nhiều yếu tố khác nhau. Trước hết dữ liệu lịch sử phải được phân tích chính xác, các xu hướng kinh tế xã hội...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chương 14 Tính toán phí bảo hiểm thuần bằng mô hình tần suất - mức độ nghiêm trọng. | Khoa Học Dữ Liệu trong Kinh tế và Kinh doanh">
<meta name="twitter:description" content="Tính toán phí của các sản phẩm bảo hiểm là một công việc phức tạp đòi hỏi phải kết hợp nhiều yếu tố khác nhau. Trước hết dữ liệu lịch sử phải được phân tích chính xác, các xu hướng kinh tế xã hội...">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><link href="libs/Lora-0.4.8/font.css" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Source%20Code%20Pro:wght@400;450&amp;display=swap" rel="stylesheet">
<script src="libs/bs3compat-0.6.1/transition.js"></script><script src="libs/bs3compat-0.6.1/tabs.js"></script><script src="libs/bs3compat-0.6.1/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script><script src="libs/d3-bundle-5.16.0/d3-bundle.min.js"></script><script src="libs/d3-lasso-0.0.5/d3-lasso.min.js"></script><script src="libs/save-svg-as-png-1.4.17/save-svg-as-png.min.js"></script><script src="libs/flatbush-4.0.0/flatbush.min.js"></script><link href="libs/ggiraphjs-0.4.6/ggiraphjs.min.css" rel="stylesheet">
<script src="libs/ggiraphjs-0.4.6/ggiraphjs.min.js"></script><script src="libs/girafe-binding-0.8.8/girafe.js"></script><script src="libs/plotly-binding-4.10.3/plotly.js"></script><script src="libs/typedarray-0.1/typedarray.min.js"></script><link href="libs/crosstalk-1.2.1/css/crosstalk.min.css" rel="stylesheet">
<script src="libs/crosstalk-1.2.1/js/crosstalk.min.js"></script><link href="libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet">
<script src="libs/plotly-main-2.11.1/plotly-latest.min.js"></script><script>
        $(function() {
            $("#toc h2").html("TRONG CHƯƠNG NÀY"); // Change text for "View source"
        });
    </script><script>
        document.addEventListener('DOMContentLoaded', function() {
            var viewSourceElement = document.getElementById('book-source');
            var editPageElement = document.getElementById('book-edit');
            var viewBookSourceElement = document.getElementById('book-repo');

            if (viewSourceElement) {
                viewSourceElement.innerText = 'Xem nguồn trang'; // Change text for "View source"
            }

            if (editPageElement) {
                editPageElement.innerText = 'Chỉnh sửa trang'; // Change text for "Edit this page"
            }

            if (viewBookSourceElement) {
                viewBookSourceElement.innerText = 'Xem nguồn sách'; // Change text for "View book source"
            }
        });
    </script><script>
        document.addEventListener('DOMContentLoaded', (event) => {
          var tocElement = document.querySelector('nav[aria-label="Table of contents"] h2');
          if (tocElement) {
            tocElement.textContent = 'Mục lục'; // Replace 'Mục lục' (Table of contents) with your desired text
          }
        });
    </script><script>
      document.addEventListener('DOMContentLoaded', (event) => {
        var tocElement = document.querySelector('nav[aria-label="Table of contents"] h2');
        if (tocElement) {
          tocElement.textContent = 'NỘI DUNG CUỐN SÁCH'; // Ensure "NỘI DUNG CUỐN SÁCH" text remains
        }
      });
    </script><script>
        document.addEventListener('DOMContentLoaded', (event) => {
          // Find the paragraph containing the original text and date
          const paragraph = document.querySelector('footer.bg-primary.text-light div.container div.row div.col-12.col-md-6.mt-3 p');

          if (paragraph) {
            // Extract the date using a regular expression
            const dateRegex = /(\d{4}-\d{2}-\d{2})/;
            const matches = paragraph.innerHTML.match(dateRegex);

            if (matches && matches.length > 1) {
              // Reformat the date from yyyy-mm-dd to dd/mm/yyyy
              const originalDate = matches[1];
              const [year, month, day] = originalDate.split('-');
              const newDate = `${day}/${month}/${year}`;

              // Replace the entire paragraph content with the new Vietnamese format
              paragraph.innerHTML = `Cuốn sách "${paragraph.querySelector('strong').innerText}" được viết bởi TS. ${paragraph.innerHTML.split('was written by ')[1].split('. ')[0]} - Trường Công nghệ - Đại học Kinh tế Quốc dân`;
            }
          }
        });
    </script><script>
        document.addEventListener('DOMContentLoaded', (event) => {
          // Find the paragraph containing the specific text
          const paragraphs = document.querySelectorAll('footer.bg-primary.text-light div.container div.row div.col-12.col-md-6.mt-3 p');
          paragraphs.forEach(paragraph => {
            if(paragraph.innerHTML.includes('This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.')) {
              // Replace the paragraph content
              paragraph.innerHTML = 'Cuốn sách này được viết bằng hoàn toàn bằng ngôn ngữ R. Phiên bản hiện tại được cập nhật vào ngày ${newDate}.';
            }
          });
        });
    </script><script src="local_edit.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
<link rel="stylesheet" href="style.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">Khoa Học Dữ Liệu trong Kinh tế và Kinh doanh</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Lời nói đầu</a></li>
<li class="book-part">PHẦN I: GIỚI THIỆU CHUNG</li>
<li><a class="" href="gi%E1%BB%9Bi-thi%E1%BB%87u-v%E1%BB%81-cu%E1%BB%91n-s%C3%A1ch.html"><span class="header-section-number">1</span> Giới thiệu về cuốn sách</a></li>
<li><a class="" href="khdl-v%C3%A0-c%C3%A1c-kh%C3%A1i-ni%E1%BB%87m-c%C6%A1-b%E1%BA%A3n.html"><span class="header-section-number">2</span> KHDL và các khái niệm cơ bản</a></li>
<li class="book-part">PHẦN II: GIỚI THIỆU VỀ R</li>
<li><a class="" href="ki%E1%BA%BFn-th%E1%BB%A9c-r-c%C6%A1-b%E1%BA%A3n.html"><span class="header-section-number">3</span> Kiến thức R cơ bản</a></li>
<li><a class="" href="ki%E1%BA%BFn-th%E1%BB%A9c-r-c%C6%A1-b%E1%BA%A3n-1.html"><span class="header-section-number">4</span> Kiến thức R cơ bản</a></li>
<li><a class="" href="ki%E1%BA%BFn-th%E1%BB%A9c-r-n%C3%A2ng-cao.html"><span class="header-section-number">5</span> Kiến thức R nâng cao</a></li>
<li class="book-part">PHẦN III: PHÂN TÍCH DỮ LIỆU</li>
<li><a class="" href="nh%E1%BA%ADp-d%E1%BB%AF-li%E1%BB%87u-v%C3%A0o-r.html"><span class="header-section-number">6</span> Nhập dữ liệu vào R</a></li>
<li><a class="" href="ti%E1%BB%81n-x%E1%BB%AD-l%C3%BD-d%E1%BB%AF-li%E1%BB%87u.html"><span class="header-section-number">7</span> Tiền xử lý dữ liệu</a></li>
<li><a class="" href="bi%E1%BA%BFn-%C4%91%E1%BB%95i-v%C3%A0-s%E1%BA%AFp-x%E1%BA%BFp-d%E1%BB%AF-li%E1%BB%87u.html"><span class="header-section-number">8</span> Biến đổi và sắp xếp dữ liệu</a></li>
<li><a class="" href="tr%E1%BB%B1c-quan-h%C3%B3a-d%E1%BB%AF-li%E1%BB%87u.html"><span class="header-section-number">9</span> Trực quan hóa dữ liệu</a></li>
<li class="book-part">PHẦN IV: MÔ HÌNH TUYẾN TÍNH</li>
<li><a class="" href="m%C3%B4-h%C3%ACnh-h%E1%BB%93i-quy-tuy%E1%BA%BFn-t%C3%ADnh.html"><span class="header-section-number">10</span> Mô hình hồi quy tuyến tính</a></li>
<li><a class="" href="c%C3%A1c-m%C3%B4-h%C3%ACnh-c%E1%BB%99ng-t%C3%ADnh-t%E1%BB%95ng-qu%C3%A1t.html"><span class="header-section-number">11</span> Các mô hình cộng tính tổng quát</a></li>
<li><a class="" href="m%C3%B4-h%C3%ACnh-tuy%E1%BA%BFn-t%C3%ADnh-t%E1%BB%95ng-qu%C3%A1t..html"><span class="header-section-number">12</span> Mô hình tuyến tính tổng quát.</a></li>
<li><a class="" href="m%C3%B4-h%C3%ACnh-t%E1%BA%A7n-su%E1%BA%A5t---m%E1%BB%A9c-%C4%91%E1%BB%99-nghi%C3%AAm-tr%E1%BB%8Dng..html"><span class="header-section-number">13</span> Mô hình tần suất - mức độ nghiêm trọng.</a></li>
<li><a class="active" href="t%C3%ADnh-to%C3%A1n-ph%C3%AD-b%E1%BA%A3o-hi%E1%BB%83m-thu%E1%BA%A7n-b%E1%BA%B1ng-m%C3%B4-h%C3%ACnh-t%E1%BA%A7n-su%E1%BA%A5t---m%E1%BB%A9c-%C4%91%E1%BB%99-nghi%C3%AAm-tr%E1%BB%8Dng..html"><span class="header-section-number">14</span> Tính toán phí bảo hiểm thuần bằng mô hình tần suất - mức độ nghiêm trọng.</a></li>
<li class="book-part">PHẦN V: MÔ HÌNH CÂY QUYẾT ĐỊNH</li>
<li><a class="" href="m%C3%B4-h%C3%ACnh-c%C3%A2y-quy%E1%BA%BFt-%C4%91%E1%BB%8Bnh.html"><span class="header-section-number">15</span> Mô hình cây quyết định</a></li>
<li><a class="" href="boosting-v%C3%A0-c%C3%A2y-quy%E1%BA%BFt-%C4%91%E1%BB%8Bnh..html"><span class="header-section-number">16</span> Boosting và cây quyết định.</a></li>
<li><a class="" href="neuralnetwork.html"><span class="header-section-number">17</span> Mô hình mạng nơ-ron</a></li>
<li><a class="" href="neuralnetwork1.html"><span class="header-section-number">18</span> Các mạng học sâu điển hình</a></li>
<li><a class="" href="h%E1%BB%8Dc-m%C3%A1y-kh%C3%B4ng-c%C3%B3-gi%C3%A1m-s%C3%A1t.html"><span class="header-section-number">19</span> Học máy không có giám sát</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/NEUKhoaToanKT/Khoa_hoc_du_lieu_trong_KTKD">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="tính-toán-phí-bảo-hiểm-thuần-bằng-mô-hình-tần-suất---mức-độ-nghiêm-trọng." class="section level1" number="14">
<h1>
<span class="header-section-number">Chương 14</span> Tính toán phí bảo hiểm thuần bằng mô hình tần suất - mức độ nghiêm trọng.<a class="anchor" aria-label="anchor" href="#t%C3%ADnh-to%C3%A1n-ph%C3%AD-b%E1%BA%A3o-hi%E1%BB%83m-thu%E1%BA%A7n-b%E1%BA%B1ng-m%C3%B4-h%C3%ACnh-t%E1%BA%A7n-su%E1%BA%A5t---m%E1%BB%A9c-%C4%91%E1%BB%99-nghi%C3%AAm-tr%E1%BB%8Dng."><i class="fas fa-link"></i></a>
</h1>
<p>Tính toán phí của các sản phẩm bảo hiểm là một công việc phức tạp đòi hỏi phải kết hợp nhiều yếu tố khác nhau. Trước hết dữ liệu lịch sử phải được phân tích chính xác, các xu hướng kinh tế xã hội cũng phải được xác định và thậm chí hoạt động của các công ty cạnh tranh cũng phải được tính đến. Các chuyên gia tính toán (hay các actuary) được đào tạo bài bản có kiến thức trong tất cả các lĩnh vực này và có khả năng đề xuất những nội dung cần thiết để phát triển và thực hiện thành công chiến lược định giá sản phẩm bảo hiểm. Trong phần này, chúng tôi sẽ minh họa quá trình tính toán ra một trong những nền tảng cơ bản nhất của một quá trình định giá, đó là xác định phí bảo hiểm thuần (Net premium). Chúng tôi sẽ xác định các khoản phí bảo hiểm thuần này dựa trên các mô hình tuyến tính tổng quát về tần suất và mức độ nghiêm trọng. Quá trình xây dựng mô hình sẽ được minh họa thông qua tất cả các giai đoạn: xác định đặc điểm dữ liệu, khai phá dữ liệu, phân tích đơn biến và đa biến, kết hợp tần suất và mức độ nghiêm trọng thành phí bảo hiểm thuần, và cuối cùng là xác thực mô hình. Các kỹ thuật mà chúng tôi minh họa có thể áp dụng rộng rãi và chúng tôi khuyến khích bạn đọc thực hành thông qua các đoạn câu lệnh được viết bằng phần mềm R.</p>
<p>Các chuyên gia tính toán phân tích dữ liệu lịch sử và giải thích các xu hướng kinh tế xã hội để xác định mức giá hợp lý của sản phẩm bảo hiểm. Những tính toán của Actuary là nền tảng cho mức giá cuối cùng mà công ty đưa ra cho khách hàng của mình. Đưa ra mức giá cuối cùng phải kết hợp nhiều yếu tố, chẳng hạn như hành động của đối thủ cạnh tranh, chiến lược tăng trưởng và sự hài lòng của người tiêu dùng, … Do đó, các chuyên gia tính toán, các nhà bảo lãnh phát hành, phòng tiếp thị phân phối sản phẩm, bộ phận tiếp nhận yêu cầu bồi thường, và ban quản lý công ty phải cùng nhau hợp tác trong việc định giá sản phẩm. Các đối tượng đa dạng này đều phải hiểu rõ các hướng tiếp cận về định giá sản phẩm để có thể đưa ra quyết định chung.</p>
<p>Trong các phần này của cuốn sách, chúng ta sẽ tập trung vào các giai đoạn đầu tiên của quá trình hình thành giá của sản phẩm bào hiểm đó là xây dựng, cải tiến, và mô hình. Kết quả của các quá trình này là tính toán ra phí bảo hiểm thuần dựa trên dữ liệu lịch sử và mô hình tuyến tính tổng quát. Sẽ có hai mô hình được xây dựng, một mô hình dành cho tần suất xảy ra sự kiện bảo hiểm và mô hình còn lại sẽ có biến mục tiêu là mức độ nghiêm trọng. Vì phí bảo hiểm thuần chỉ phản ánh dữ liệu lịch sử nên sẽ không phù hợp để sử dụng làm dự báo giá cho tương lai do không tính toán đến các xu hướng kinh tế xã hội trong khoảng thời gian tiếp theo. Phí bảo hiểm thuần cũng không tính toán đến các chi phí, chi phí vốn rủi ro, hay lợi nhuận biên cần thiết để giúp công ty tồn tại trên thị trường.</p>
<p>Chương sách này được cấu trúc như sau: trước hết, chúng tôi mô tả các đặc điểm chính của tập dữ liệu mà chúng ta sử dụng làm cơ sở xây dựng mô hình. Điều này giúp bạn đọc có hiểu biết tổng quan về dữ liệu lịch sử. Tiếp theo, chúng tôi thực hiện các phân tích khai phá các biến trong tập dữ liệu. Đây là tập dữ liệu về bào hiểm đối với các xe ô tô chở khách tư nhân có nhiều đặc điểm điển hình mà bạn sẽ gặp phải mỗi khi làm việc với dữ liệu bảo hiểm. Những hiểu biết về dữ liệu bạn thu được khi khai phá dữ liệu về các biến riêng và mối quan hệ giữa các biến sẽ phục vụ tốt cho bạn trong giai đoạn xây dựng mô hình. Sau phân tích khai phá, chúng ta sẽ bắt đầu xây dựng các mô hình: mô hình cho tần suất và và mô hình cho mức độ nghiêm trọng tương ứng. Các mô hình sẽ được xây dựng từ đơn giản đến phức tạp, bắt đầu với các mô hình một biến và chuyển sang phân tích mô hình đa biến. Những mô hình chúng tôi xây dựng không nhất thiết phải là những mô hình tốt nhất và chúng tôi khuyến khích bạn đọc tự khám phá và cố gắng tạo ra những mô hình tốt hơn. Sau cùng, chúng ta sẽ kết hợp các mô hình tần suất và mức độ nghiêm trọng để tạo ra phí bảo hiểm thuần túy và xác thực mô hình trên tập dữ liệu ngoài mẫu.</p>
<div id="dữ-liệu-để-xây-dựng-mô-hình" class="section level2" number="14.1">
<h2>
<span class="header-section-number">14.1</span> Dữ liệu để xây dựng mô hình<a class="anchor" aria-label="anchor" href="#d%E1%BB%AF-li%E1%BB%87u-%C4%91%E1%BB%83-x%C3%A2y-d%E1%BB%B1ng-m%C3%B4-h%C3%ACnh"><i class="fas fa-link"></i></a>
</h2>
<p>Tập dữ liệu “pricing-modeling-dataset.csv” được sử dụng làm dữ liệu để chúng ta phân tích và xây dựng các mô hình tuyến tính tổng quát. Bộ dữ liệu bao gồm thông tin về các hợp đồng bảo hiểm ô tô chở khách thương mại và chứa cả thông tin về yêu cầu bồi thường. Dữ liệu được quan sát trong các năm từ 2010 đến 2013. Có tổng cộng 40,760 hàng và 24 biến.</p>
<div class="sourceCode" id="cb854"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">dat</span><span class="op">&lt;-</span><span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"../KHDL_KTKD Final/Dataset/pricing-modeling-dataset.csv"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">dat</span><span class="op">)</span></span></code></pre></div>
<pre><code>## # A tibble: 6 × 24
##   pol.id   year exposure nb.rb driver.age driver.gender marital.status
##   &lt;chr&gt;   &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;      &lt;dbl&gt; &lt;chr&gt;         &lt;chr&gt;         
## 1 POL0001  2010   1      RB            63 Male          Married       
## 2 POL0002  2010   1      NB            33 Male          Married       
## 3 POL0003  2010   1      RB            68 Male          Married       
## 4 POL0004  2010   0.0833 RB            68 Male          Married       
## 5 POL0005  2010   1      RB            68 Male          Married       
## 6 POL0006  2010   0.0833 RB            68 Male          Married       
## # ℹ 17 more variables: yrs.licensed &lt;dbl&gt;, ncd.level &lt;dbl&gt;, region &lt;dbl&gt;,
## #   body.code &lt;chr&gt;, vehicle.age &lt;dbl&gt;, vehicle.value &lt;dbl&gt;, seats &lt;dbl&gt;,
## #   ccm &lt;dbl&gt;, hp &lt;dbl&gt;, weight &lt;dbl&gt;, length &lt;dbl&gt;, width &lt;dbl&gt;, height &lt;dbl&gt;,
## #   fuel.type &lt;chr&gt;, prior.claims &lt;dbl&gt;, clm.count &lt;dbl&gt;, clm.incurred &lt;dbl&gt;</code></pre>
<p>Cần lưu ý là một hàng dữ liệu có thể thể hiện nhiều yêu cầu bồi thường từ một đối tượng được bảo hiểm. Biến <span class="math inline">\(clm.count\)</span> đo lường số lượng yêu cầu bồi thường và biến <span class="math inline">\(clm.incurred\)</span> là tổng số tiền thanh toán yêu cầu bồi thường và bao gồm cả các khoản cần phải thanh toán trong tương lai. Các biến độc lập của dữ liệu có thể được nhóm thành bốn loại: biến điều khiển, biến đặc điểm người lái, biến đặc điểm địa lý, và biến đặc điểm phương tiện. Bảng dưới đây cho biết tên các biến trong tập dữ liệu</p>
<div class="inline-table"><table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-4">Bảng 2.2: </span>Các biến trong dữ liệu lịch sử
</caption>
<thead><tr>
<th style="text-align:left;">
Biến mục tiêu
</th>
<th style="text-align:left;">
Biến điều khiển
</th>
<th style="text-align:left;">
Đặc điểm người lái
</th>
<th style="text-align:left;">
Đặc điểm phương tiện
</th>
<th style="text-align:left;">
Đặc điểm địa lý
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
clm.count
</td>
<td style="text-align:left;">
pol.id
</td>
<td style="text-align:left;">
nb.rb
</td>
<td style="text-align:left;">
body.code
</td>
<td style="text-align:left;">
region
</td>
</tr>
<tr>
<td style="text-align:left;">
clm.incurred
</td>
<td style="text-align:left;">
year
</td>
<td style="text-align:left;">
driver.age
</td>
<td style="text-align:left;">
vehicle.age
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
exposure
</td>
<td style="text-align:left;">
driver.gender
</td>
<td style="text-align:left;">
vehicle.value
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
marital.status
</td>
<td style="text-align:left;">
seats
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
yrs.licensed
</td>
<td style="text-align:left;">
ccm
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
ncd.level
</td>
<td style="text-align:left;">
hp
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
prior.claims
</td>
<td style="text-align:left;">
weight
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
length
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
width
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
height
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
fuel.type
</td>
<td style="text-align:left;">
</td>
</tr>
</tbody>
</table></div>
<p>Biến <span class="math inline">\(year\)</span> cho biết năm (năm dương lịch) mà xe ô tô chở khách được bảo hiểm và biến <span class="math inline">\(exposure\)</span> đo lường khoảng thời gian (đo bằng năm) mà xe ô tô được bảo vệ trong năm dương lịch. Chúng ta chỉ có một biến địa lý là <span class="math inline">\(region\)</span> cho chúng ta biết địa điểm (gara đăng ký) của xe. Điều đáng tiếc là biến <span class="math inline">\(region\)</span> đã được mã hóa thành số và chúng ta không có bất kỳ thông tin nào về mối liên hệ về không gian của các vùng này. Đây là một nhược điểm đáng kể đối với tập dữ liệu mà chúng ta có. Xin được nhắc lại rằng việc chuẩn bị dữ liệu tốt trước khi xây dựng mô hình là rất quan trọng nên loại bỏ biến chỉ thực hiện khi chúng ta chắc chắn rằng biến không có chứa thông tin hữu ích.</p>
<p>Các biến đặc tính của người lái xe bao gồm độ tuổi (<span class="math inline">\(driver.age\)</span>), giới tính (<span class="math inline">\(driver.gender\)</span>) của người điều khiển phương tiện, tình trạng hôn nhân (<span class="math inline">\(marital.status\)</span>), số năm mà người điều khiển phương tiện đã được cấp phép (<span class="math inline">\(yrs.licensed\)</span>), mức chiết khấu khi không yêu cầu bồi thường <span class="math inline">\(ncd.level\)</span> (giá trị cao hơn phản ánh mức chiết khấu lớn hơn khi không có bất kỳ yêu cầu nào) và số lượng yêu cầu gửi trước đó <span class="math inline">\(prior.claims\)</span>. Biến <span class="math inline">\(nb.rb\)</span> cho chúng ta biết hợp đồng này là hoạt động kinh doanh mới (nb) hay hoạt động kinh doanh tái tục (rb).</p>
<p>Các biến đặc tính của xe đo lường các thuộc tính khác nhau như kiểu dáng thân xe (<span class="math inline">\(body.code\)</span>); tuổi và giá trị của xe (<span class="math inline">\(vehicle.age\)</span> và <span class="math inline">\(vehicle.value\)</span>); số lượng chỗ ngồi (<span class="math inline">\(seats\)</span>); và trọng lượng (<span class="math inline">\(weight\)</span>), chiều dài (<span class="math inline">\(length\)</span>), chiều rộng (<span class="math inline">\(width\)</span>) và chiều cao (<span class="math inline">\(height\)</span>) của xe. Các biến <span class="math inline">\(ccm\)</span>, <span class="math inline">\(hp\)</span> và <span class="math inline">\(fuel.type\)</span> lần lượt đo kích thước của động cơ theo xăng-ti-mét khối, mã lực và loại nhiên liệu (xăng, dầu diesel hoặc khí hóa lỏng).</p>
<p>Như đã giới thiệu ở trên, hai biến mục tiêu là <span class="math inline">\(clm.count\)</span> và <span class="math inline">\(clm.incurred\)</span>, cho biết số lần gửi yêu cầu bồi thường và tổng chi phí cuối cùng của những yêu cầu đó. Tất cả các biến trong tập dữ liệu đều có thể được phân loại là liên tục hoặc rời rạc. Các bảng dưới đây trình bày một số thông tin và chỉ số thống kê cho 14 biến liên tục và 12 biến rời rạc:</p>
<div class="inline-table"><table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-5">Bảng 14.1: </span>Các biến kiểu số
</caption>
<thead><tr>
<th style="text-align:right;">
Tên biến
</th>
<th style="text-align:right;">
Trung bình
</th>
<th style="text-align:right;">
Phương sai
</th>
<th style="text-align:right;">
Giá trị min
</th>
<th style="text-align:right;">
Giá trị max
</th>
<th style="text-align:right;">
Trung vị
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:right;">
exposure
</td>
<td style="text-align:right;">
0.51
</td>
<td style="text-align:right;">
0.27
</td>
<td style="text-align:right;">
0.08
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:right;">
0.50
</td>
</tr>
<tr>
<td style="text-align:right;">
driver.age
</td>
<td style="text-align:right;">
44.55
</td>
<td style="text-align:right;">
10.78
</td>
<td style="text-align:right;">
18.00
</td>
<td style="text-align:right;">
93.00
</td>
<td style="text-align:right;">
44.00
</td>
</tr>
<tr>
<td style="text-align:right;">
yrs.licensed
</td>
<td style="text-align:right;">
3.21
</td>
<td style="text-align:right;">
1.89
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:right;">
10.00
</td>
<td style="text-align:right;">
3.00
</td>
</tr>
<tr>
<td style="text-align:right;">
vehicle.age
</td>
<td style="text-align:right;">
3.26
</td>
<td style="text-align:right;">
2.59
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
18.00
</td>
<td style="text-align:right;">
3.00
</td>
</tr>
<tr>
<td style="text-align:right;">
vehicle.value
</td>
<td style="text-align:right;">
23.50
</td>
<td style="text-align:right;">
8.89
</td>
<td style="text-align:right;">
4.50
</td>
<td style="text-align:right;">
132.60
</td>
<td style="text-align:right;">
22.10
</td>
</tr>
<tr>
<td style="text-align:right;">
ccm
</td>
<td style="text-align:right;">
1670.69
</td>
<td style="text-align:right;">
390.12
</td>
<td style="text-align:right;">
970.00
</td>
<td style="text-align:right;">
3198.00
</td>
<td style="text-align:right;">
1560.00
</td>
</tr>
<tr>
<td style="text-align:right;">
hp
</td>
<td style="text-align:right;">
86.38
</td>
<td style="text-align:right;">
19.62
</td>
<td style="text-align:right;">
42.00
</td>
<td style="text-align:right;">
200.00
</td>
<td style="text-align:right;">
75.00
</td>
</tr>
<tr>
<td style="text-align:right;">
weight
</td>
<td style="text-align:right;">
1364.22
</td>
<td style="text-align:right;">
222.01
</td>
<td style="text-align:right;">
860.00
</td>
<td style="text-align:right;">
2275.00
</td>
<td style="text-align:right;">
1320.00
</td>
</tr>
<tr>
<td style="text-align:right;">
length
</td>
<td style="text-align:right;">
4.32
</td>
<td style="text-align:right;">
0.36
</td>
<td style="text-align:right;">
1.80
</td>
<td style="text-align:right;">
6.94
</td>
<td style="text-align:right;">
4.28
</td>
</tr>
<tr>
<td style="text-align:right;">
width
</td>
<td style="text-align:right;">
1.78
</td>
<td style="text-align:right;">
0.10
</td>
<td style="text-align:right;">
1.48
</td>
<td style="text-align:right;">
2.12
</td>
<td style="text-align:right;">
1.74
</td>
</tr>
<tr>
<td style="text-align:right;">
height
</td>
<td style="text-align:right;">
1.81
</td>
<td style="text-align:right;">
0.09
</td>
<td style="text-align:right;">
1.42
</td>
<td style="text-align:right;">
2.52
</td>
<td style="text-align:right;">
1.82
</td>
</tr>
<tr>
<td style="text-align:right;">
prior.claims
</td>
<td style="text-align:right;">
0.83
</td>
<td style="text-align:right;">
1.33
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
20.00
</td>
<td style="text-align:right;">
0.00
</td>
</tr>
<tr>
<td style="text-align:right;">
clm.count
</td>
<td style="text-align:right;">
0.08
</td>
<td style="text-align:right;">
0.30
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
5.00
</td>
<td style="text-align:right;">
0.00
</td>
</tr>
<tr>
<td style="text-align:right;">
clm.incurred
</td>
<td style="text-align:right;">
66.52
</td>
<td style="text-align:right;">
406.23
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
11683.58
</td>
<td style="text-align:right;">
0.00
</td>
</tr>
</tbody>
</table></div>
<div class="inline-table"><table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-6">Bảng 14.2: </span>Các biến kiểu rời rạc
</caption>
<thead><tr>
<th style="text-align:right;">
Tên biến
</th>
<th style="text-align:right;">
Số giá trị rời rạc
</th>
<th style="text-align:right;">
Giá trị mode
</th>
<th style="text-align:right;">
Các giá trị điển hình
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:right;">
year
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
2012
</td>
<td style="text-align:right;">
2010,2011,2012,2013
</td>
</tr>
<tr>
<td style="text-align:right;">
nb.rb
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
NB
</td>
<td style="text-align:right;">
NB,RB
</td>
</tr>
<tr>
<td style="text-align:right;">
driver.gender
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
Male
</td>
<td style="text-align:right;">
Female,Male
</td>
</tr>
<tr>
<td style="text-align:right;">
marital.status
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
Married
</td>
<td style="text-align:right;">
Divorced,Married,Single,Widow
</td>
</tr>
<tr>
<td style="text-align:right;">
ncd.level
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1,2,3,4,5
</td>
</tr>
<tr>
<td style="text-align:right;">
region
</td>
<td style="text-align:right;">
38
</td>
<td style="text-align:right;">
17
</td>
<td style="text-align:right;">
1,2,3,4,5
</td>
</tr>
<tr>
<td style="text-align:right;">
body.code
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
A
</td>
<td style="text-align:right;">
A,B,C,D,E
</td>
</tr>
<tr>
<td style="text-align:right;">
seats
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
2,3,4,5,6
</td>
</tr>
<tr>
<td style="text-align:right;">
fuel.type
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
Diesel
</td>
<td style="text-align:right;">
Diesel,Gasoline,LPG
</td>
</tr>
</tbody>
</table></div>
Thống kê chung về tần suất và mức độ nghiêm trọng theo năm được cho trong bảng phía dưới:
<div class="inline-table"><table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-7">Bảng 14.3: </span>Tần suất và mức độ nghiêm trọng trung bình theo năm
</caption>
<thead><tr>
<th style="text-align:right;">
Năm
</th>
<th style="text-align:right;">
Exposure
</th>
<th style="text-align:right;">
Số yêu cầu
</th>
<th style="text-align:right;">
Tổng giá trị
</th>
<th style="text-align:right;">
Tần suất
</th>
<th style="text-align:right;">
Mức độ nghiêm trọng
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:right;">
2010
</td>
<td style="text-align:right;">
3661.9
</td>
<td style="text-align:right;">
422
</td>
<td style="text-align:right;">
287868.9
</td>
<td style="text-align:right;">
0.115
</td>
<td style="text-align:right;">
78.612
</td>
</tr>
<tr>
<td style="text-align:right;">
2011
</td>
<td style="text-align:right;">
5221.7
</td>
<td style="text-align:right;">
551
</td>
<td style="text-align:right;">
314430.6
</td>
<td style="text-align:right;">
0.106
</td>
<td style="text-align:right;">
60.216
</td>
</tr>
<tr>
<td style="text-align:right;">
2012
</td>
<td style="text-align:right;">
6527.2
</td>
<td style="text-align:right;">
1278
</td>
<td style="text-align:right;">
1021151.8
</td>
<td style="text-align:right;">
0.196
</td>
<td style="text-align:right;">
156.446
</td>
</tr>
<tr>
<td style="text-align:right;">
2013
</td>
<td style="text-align:right;">
5386.2
</td>
<td style="text-align:right;">
1180
</td>
<td style="text-align:right;">
1087735.2
</td>
<td style="text-align:right;">
0.219
</td>
<td style="text-align:right;">
201.949
</td>
</tr>
<tr>
<td style="text-align:right;">
Total
</td>
<td style="text-align:right;">
20797.1
</td>
<td style="text-align:right;">
3431
</td>
<td style="text-align:right;">
2711186.6
</td>
<td style="text-align:right;">
0.165
</td>
<td style="text-align:right;">
130.364
</td>
</tr>
</tbody>
</table></div>
<p>Lưu ý rằng khối lượng kinh doanh đã tăng khoảng 78% từ năm 2010 đến năm 2012 và sau đó giảm 17% vào năm 2013. Tần suất trong hai năm đầu tiên là khoảng 11% và sau đó tăng đáng kể lên khoảng 20%. Mức độ nghiêm trọng trung bình trong tất cả các năm dương lịch là 790, nhưng có mức tăng mạnh theo thời gian, ngoại trừ năm 2011.</p>
<p>Thông thường quá trình xây dựng và xác thực mô hình sẽ cần chia dữ liệu của thành ba phần: tập dữ liệu huấn luyện (training dataset), tập dữ liệu kiểm tra mô hình (test dataset) và tập dữ liệu xác thực mô hình (validation dataset). Lưu ý rằng việc phân chia dữ liệu thành ba phần chỉ khả thi khi có một lượng lớn dữ liệu. Trong trường hợp của dữ liệu ở trên, chúng ta chỉ có khoảng 41.000 quan sát trong bốn năm dương lịch. Đây là một tập dữ liệu không đủ lớn, vì vậy chúng tôi sẽ sử dụng phương pháp tập xác thực. Thay vì chia dữ liệu thành ba tập, chúng ta sẽ chỉ chia dữ liệu thành hai tập: tập huấn luyện và tập xác thực. Tập dữ liệu huấn luyện để phát triển và thử nghiệm các mô hình chứa 70% dữ liệu. 30% dữ liệu được sử dụng để kiểm tra mô hình. Trong xác thực chéo, chúng tôi chia dữ liệu huấn luyện của mình thành năm tập hợp con (5-folds) và gắn nhãn cho các tập này từ 1 đến 5. Tham số cuối cùng của mô hình được sử dụng là giá trị trung bình của các tham số được ước lượng ra từ mỗi lần xác thực chéo.</p>
</div>
<div id="phân-tích-khai-phá-dữ-liệu" class="section level2" number="14.2">
<h2>
<span class="header-section-number">14.2</span> Phân tích khai phá dữ liệu<a class="anchor" aria-label="anchor" href="#ph%C3%A2n-t%C3%ADch-khai-ph%C3%A1-d%E1%BB%AF-li%E1%BB%87u"><i class="fas fa-link"></i></a>
</h2>
<p>Trong phần này, chúng ta bắt đầu bằng cách khai phá các biến riêng lẻ để hiểu rõ hơn về thông tin có trong tập dữ liệu của mình. Trong quá trình phân tích dữ liệu, chúng ta sẽ tập trung vào việc tìm hiểu mức độ phổ biến của từng biến, loại giá trị mà mỗi biến nhận, cách mã hóa các giá trị còn thiếu và mối quan hệ qua lại giữa các biến.</p>
<div id="biến-tần-suất-và-mối-liên-hệ-đến-các-biến-khác" class="section level3" number="14.2.1">
<h3>
<span class="header-section-number">14.2.1</span> Biến tần suất và mối liên hệ đến các biến khác<a class="anchor" aria-label="anchor" href="#bi%E1%BA%BFn-t%E1%BA%A7n-su%E1%BA%A5t-v%C3%A0-m%E1%BB%91i-li%C3%AAn-h%E1%BB%87-%C4%91%E1%BA%BFn-c%C3%A1c-bi%E1%BA%BFn-kh%C3%A1c"><i class="fas fa-link"></i></a>
</h3>
<p>Từ phần trước, chúng ta biết rằng tần suất chung của toàn bộ tập dữ liệu là 16,5%. Do chúng ta xây dựng mô hình dựa trên cách tiếp cận xác thực chéo nên dữ liệu xây dựng mô hình chỉ bao gồm 70% dữ liệu hiện có. Chúng ta chia dữ liệu một cách ngẫu nhiên như sau</p>
<div class="sourceCode" id="cb856"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Đổi các biến rời rạc về kiểu factor</span></span>
<span><span class="va">factor.variable</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"year"</span>,<span class="st">"nb.rb"</span>,<span class="st">"driver.gender"</span>,<span class="st">"marital.status"</span>,<span class="st">"ncd.level"</span>,<span class="st">"region"</span>,</span>
<span>      <span class="st">"body.code"</span>,<span class="st">"seats"</span>,<span class="st">"fuel.type"</span><span class="op">)</span></span>
<span><span class="va">dat</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="va">dat</span><span class="op">)</span></span>
<span><span class="kw">for</span> <span class="op">(</span><span class="va">i</span> <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">ncol</a></span><span class="op">(</span><span class="va">dat</span><span class="op">)</span><span class="op">)</span><span class="op">{</span></span>
<span>  <span class="kw">if</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">dat</span><span class="op">)</span><span class="op">[</span><span class="va">i</span><span class="op">]</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="va">factor.variable</span><span class="op">)</span><span class="op">{</span></span>
<span>    <span class="va">dat</span><span class="op">[</span>,<span class="va">i</span><span class="op">]</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="va">dat</span><span class="op">[</span>,<span class="va">i</span><span class="op">]</span><span class="op">)</span></span>
<span>  <span class="op">}</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="co"># Chia dữ liệu thành hai phần, dữ liệu huấn luyện mô hình và dữ liệu xác thực mô hình</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">10</span><span class="op">)</span></span>
<span><span class="va">train.index</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">dat</span><span class="op">)</span>,size <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fl">0.7</span><span class="op">*</span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">dat</span><span class="op">)</span>,<span class="fl">0</span><span class="op">)</span>,replace <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="va">training.dat</span><span class="op">&lt;-</span><span class="va">dat</span><span class="op">[</span><span class="va">train.index</span>,<span class="op">]</span></span>
<span><span class="va">test.dat</span><span class="op">&lt;-</span><span class="va">dat</span><span class="op">[</span><span class="op">-</span><span class="va">train.index</span>,<span class="op">]</span></span>
<span><span class="co"># Tần suất trung bình trên tập dữ liệu huấn luyện</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">training.dat</span><span class="op">$</span><span class="va">clm.count</span><span class="op">)</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">training.dat</span><span class="op">$</span><span class="va">exposure</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 0.1635727</code></pre>
<p>Trên tập dữ liệu huấn luyện, tần suất trung bình là 16,35% rất gần với tần suất chung ở phần trước. Quá trình khai phá dữ liệu là quá trình tìm hiểu biến tần suất phụ thuộc như thế nào vào các biến số mà chúng ta có trong dữ liệu. Hãy bắt đầu bằng cách xem xét biến <span class="math inline">\(nb.rb\)</span>. Đây là một biến chỉ báo cho chúng ta biết hợp đồng bảo hiểm là hoạt động khai thác mới (NB) hay là hợp đồng tái tục (RB). Tần suất trong tập dữ liệu huấn luyện của chúng tôi theo chỉ số khai thác mới hoặc tái tục này nằm trong bảng dưới đây</p>
<div class="inline-table"><table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-9">Bảng 14.4: </span>Tần suất trung bình theo năm của hợp đồng khai thác mới và tái tục
</caption>
<thead><tr>
<th style="text-align:right;">
Năm
</th>
<th style="text-align:right;">
HĐ mới/Tái tục
</th>
<th style="text-align:right;">
Exposure
</th>
<th style="text-align:right;">
Số yêu cầu
</th>
<th style="text-align:right;">
Tần suất
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:right;">
2010
</td>
<td style="text-align:right;">
NB
</td>
<td style="text-align:right;">
2477.3
</td>
<td style="text-align:right;">
306
</td>
<td style="text-align:right;">
0.124
</td>
</tr>
<tr>
<td style="text-align:right;">
2010
</td>
<td style="text-align:right;">
RB
</td>
<td style="text-align:right;">
1184.6
</td>
<td style="text-align:right;">
116
</td>
<td style="text-align:right;">
0.098
</td>
</tr>
<tr>
<td style="text-align:right;">
2011
</td>
<td style="text-align:right;">
NB
</td>
<td style="text-align:right;">
3475.4
</td>
<td style="text-align:right;">
440
</td>
<td style="text-align:right;">
0.127
</td>
</tr>
<tr>
<td style="text-align:right;">
2011
</td>
<td style="text-align:right;">
RB
</td>
<td style="text-align:right;">
1746.3
</td>
<td style="text-align:right;">
111
</td>
<td style="text-align:right;">
0.064
</td>
</tr>
<tr>
<td style="text-align:right;">
2012
</td>
<td style="text-align:right;">
NB
</td>
<td style="text-align:right;">
4389.6
</td>
<td style="text-align:right;">
934
</td>
<td style="text-align:right;">
0.213
</td>
</tr>
<tr>
<td style="text-align:right;">
2012
</td>
<td style="text-align:right;">
RB
</td>
<td style="text-align:right;">
2137.7
</td>
<td style="text-align:right;">
344
</td>
<td style="text-align:right;">
0.161
</td>
</tr>
<tr>
<td style="text-align:right;">
2013
</td>
<td style="text-align:right;">
NB
</td>
<td style="text-align:right;">
3762.1
</td>
<td style="text-align:right;">
953
</td>
<td style="text-align:right;">
0.253
</td>
</tr>
<tr>
<td style="text-align:right;">
2013
</td>
<td style="text-align:right;">
RB
</td>
<td style="text-align:right;">
1624.1
</td>
<td style="text-align:right;">
227
</td>
<td style="text-align:right;">
0.140
</td>
</tr>
<tr>
<td style="text-align:right;">
Total
</td>
<td style="text-align:right;">
NB
</td>
<td style="text-align:right;">
14104.4
</td>
<td style="text-align:right;">
2633
</td>
<td style="text-align:right;">
0.187
</td>
</tr>
<tr>
<td style="text-align:right;">
Total
</td>
<td style="text-align:right;">
RB
</td>
<td style="text-align:right;">
6692.7
</td>
<td style="text-align:right;">
798
</td>
<td style="text-align:right;">
0.119
</td>
</tr>
</tbody>
</table></div>
<p>Có thể thấy rằng trong dữ liệu đào tạo, tần suất trung bình của với hợp đồng khai thác mới là 18,7% và của các hợp đồng tái tục là 11,9%. Đây là một sự khác biệt đáng kể, do đó biến <span class="math inline">\(rb.nb\)</span> này là một lựa chọn tốt để đưa vào mô hình.</p>
<p>Tiếp theo, chúng ta quan tâm đến biến vị trí địa lý <span class="math inline">\(region\)</span>. Mặc dù vị trí địa lý đã được mã hóa bằng các số tự nhiên từ 1 đến 38 và chúng ta không biết được vị trí thực sự của các vùng. Tuy nhiên, có sự phân bố không đồng đều về tần suất xảy ra tai nạn giữa các vùng địa lý theo thời gian. Thật vậy, hình vẽ dưới đây mô tả điều đó</p>
<div class="inline-figure">
<img src="10-Ung-dung-GLM_files/figure-html/unnamed-chunk-10-1.png" width="1152" style="display: block; margin: auto;">
Có thể thấy rằng có sự khác nhau rõ rệt về tần suất xảy ra tai nạn giữa các vùng, và tần suất cũng có sự thay đổi theo thời gian. Do đó, không nên loại bỏ biến vùng ra khỏi dữ liệu xây dựng mô hình.</div>
<p>Tiếp theo chúng ta xem xét <span class="math inline">\(driver.age\)</span>. Biến này cho chúng ta biết tuổi của người điều khiển chính phương tiện. Trong dữ liệu huấn luyện mô hình, chúng ta có độ tuổi từ 18 đến 89 và tuổi 93(!), tổng cộng có 73 độ tuổi duy nhất. Khi gặp dữ liệu như vậy, chúng ta nên nghi ngờ những độ tuổi rất cao này và cần kiểm tra xem dữ liệu có chính xác không. Ngoài ra, chúng ta cũng nên kiểm tra tổng số exposure theo từng độ tuổi.</p>
<div class="inline-figure"><img src="10-Ung-dung-GLM_files/figure-html/unnamed-chunk-11-1.png" width="1152" style="display: block; margin: auto;"></div>
<p>Có thể thấy rằng khi tổng số exposure nhỏ thì tần suất có biến động rất mạnh, điển hình là độ tuổi dưới 25 và trên 60. Độ tuổi có tần suất tai nạn cao nhất không được thể hiện trong đồ thị ở trên là tuổi 19 với tần suất là 182%, tuy nhiên tổng exposure cho độ tuổi này chỉ là 2,2 năm nên tần suất không có ý nghĩa thống kê. Nhìn chung có sự giảm dần của tần suất xảy ra tai nạn khi độ tuổi trung bình. Bạn đọc có thể quan sát thấy rằng đường thẳng mô tả mối quan hệ tuyến tính giữa tần suất và độ tuổi có độ dốc âm. Như vậy <span class="math inline">\(driver.age\)</span> cũng là biến cần đưa vào mô hình.</p>
<p>Các biến liên quan đến đặc điểm người lái xe còn có giới tính của người lái xe (<span class="math inline">\(driver.gender\)</span>) và tình trạng hôn nhân (<span class="math inline">\(marital.status\)</span>. Mối liên hệ của các biến và tần suất được mô tả như đồ thị dưới đây</p>
<div class="inline-figure"><img src="10-Ung-dung-GLM_files/figure-html/unnamed-chunk-12-1.png" width="672" style="display: block; margin: auto;"></div>
<p>Có thể thấy rằng tần suất gây ra tai nạn của lái xe nữ là cao hơn so với lái xe nam, sự khác biệt là tương đối rõ trong nhóm những người đã lập gia đình hoặc chưa từng lập gia đình. Cũng giống như kinh nghiệm nghiên cứu từ nhiều dữ liệu khác, nhóm những người góa vợ/chồng có tần suất gây ra tai nạn cao hơn đáng kể so với nhóm khác. Có thể nhận xét rằng tình trạng hôn nhân và giới tính của người lái xe có ảnh hưởng đến tần suất mặc dù ảnh hưởng không rõ ràng như các biến khác.</p>
<p>Chúng ta có thể tiếp tục quá trình trên cho các biến khác liên quan đến người lái xe. Tuy nhiên, mục tiêu cuối cùng sẽ là xây dựng mô hình cho biến tần suất, do đó, bạn đọc có thể dựa trên các nguyên tắc ở trên để nghiên cứu mối liên hệ của các biến khác lên tần suất xảy ra tai nạn. Quá trình khai phá dữ liệu có ý nghĩa quan trọng trong việc lựa chọn đưa biến vào trong mô hình nhất là với các dữ liệu có nhiều biến. Bạn đọc có thể tiếp tục quá trình này với các biến liên quan đến đặc điểm của xe.</p>
</div>
<div id="biến-mức-độ-nghiêm-trọng-và-mối-liên-hệ-với-các-biến-khác" class="section level3" number="14.2.2">
<h3>
<span class="header-section-number">14.2.2</span> Biến mức độ nghiêm trọng và mối liên hệ với các biến khác<a class="anchor" aria-label="anchor" href="#bi%E1%BA%BFn-m%E1%BB%A9c-%C4%91%E1%BB%99-nghi%C3%AAm-tr%E1%BB%8Dng-v%C3%A0-m%E1%BB%91i-li%C3%AAn-h%E1%BB%87-v%E1%BB%9Bi-c%C3%A1c-bi%E1%BA%BFn-kh%C3%A1c"><i class="fas fa-link"></i></a>
</h3>
<p>Dữ liệu sử dụng để xây dựng mô hình cho mức độ nghiêm trọng chỉ bao gồm các hợp đồng có xảy ra yêu cầu bồi thường. Trong dữ liệu dùng để huấn luyện mô hình, có 2209 hợp đồng nằm trong phạm vi. Giá trị tiền bồi thường trung bình trên mỗi yêu cầu bồi thường là 800,57
<span class="math display">\[\begin{align}
\cfrac{\textit{Tổng chi phí}}{\textit{Tổng số yêu cầu}} = \cfrac{1.906.958}{2382} = 800,57
\end{align}\]</span></p>
<p>Trước hết, chúng ta xem xét biến <span class="math inline">\(nb.rb\)</span> có tác động lên mức độ nghiêm trọng hay không. Bảng dưới đây cho biết số lượng yêu cầu bồi thường, tổng mức bồi thường và giá trị tiền bồi thường trung bình của các hợp đồng bán mới và các hợp đồng tái tục.</p>
<div class="inline-table"><table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-13">Bảng 14.5: </span>Mức độ nghiêm trọng trung bình của hợp đồng khai thác mới và tái tục
</caption>
<thead><tr>
<th style="text-align:right;">
HĐ mới/Tái tục
</th>
<th style="text-align:right;">
Tổng giá trị
</th>
<th style="text-align:right;">
Số yêu cầu
</th>
<th style="text-align:right;">
Mức nghiêm trọng
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:right;">
NB
</td>
<td style="text-align:right;">
1530245.4
</td>
<td style="text-align:right;">
1848
</td>
<td style="text-align:right;">
828.055
</td>
</tr>
<tr>
<td style="text-align:right;">
RB
</td>
<td style="text-align:right;">
376712.6
</td>
<td style="text-align:right;">
534
</td>
<td style="text-align:right;">
705.454
</td>
</tr>
</tbody>
</table></div>
<p>Có thể thấy rằng mức độ nghiêm trọng trung bình của các hợp đồng khai thác mới (828) cao hơn đáng kể so với các hợp đồng tái tục (705). Điều này cho thấy biến <span class="math inline">\(nb.rb\)</span> là biến có ý nghĩa giải thích trong mô hình hóa mức độ nghiêm trọng của yêu cầu bảo hiểm.</p>
<p>Việc phân tích các biến liên quan đến đặc điểm của người lái xe hoàn toàn được thực hiện tương tự như đối với biến tần suất nên chúng tôi sẽ không lặp lại. Việc lựa chọn các biến đưa vào mô hình tần suất sẽ được tiếp tục thảo luận trong phần xây dựng mô hình.</p>
</div>
</div>
<div id="mô-hình-tuyến-tính-tổng-quát-cho-tần-suất." class="section level2" number="14.3">
<h2>
<span class="header-section-number">14.3</span> Mô hình tuyến tính tổng quát cho tần suất.<a class="anchor" aria-label="anchor" href="#m%C3%B4-h%C3%ACnh-tuy%E1%BA%BFn-t%C3%ADnh-t%E1%BB%95ng-qu%C3%A1t-cho-t%E1%BA%A7n-su%E1%BA%A5t."><i class="fas fa-link"></i></a>
</h2>
<p>Khi phân tích khai phá dữ liêu, chúng ta biết rằng biến tần suất tập dữ liệu huấn luyện có giá trị trung bình là 16,4% và có một số biến có thể là phù hợp để đưa vào mô hình bao gồm tuổi của người lái xe hoặc chỉ số cho biết hợp đồng là bán mới hay tái tục. Chúng ta sẽ bắt đầu xây dựng mô hình tần số bằng cách thực hiện phân tích mô hình có một biến độc lập duy nhất, sau đó sẽ chuyển sang xây dựng mô hình có nhiều biến độc lập bằng cách bổ sung thêm các biến có ý nghĩa khác. Xây dựng mô hình có một biến độc lập là bước quan trọng để chúng ta có nhận định chính xác về khả năng giải thích của các biến độc lập và cách biến đổi các biến độc lập để tăng khả năng giải thích trước khi xây dựng mô hình có nhiều biến độc lập</p>
<p>Trước khi nói đến biến độc lập, chúng ta cần đưa ra lựa chọn cho hàm liên kết và phân phối cho biến tần suất. Đối với hầu hết các mô hình tính toán phí bảo hiểm thuần, chúng ta muốn có biến phụ thuộc được giải thích bởi biến phụ thuộc thông qua quy tắc nhân, do đó chúng ta sẽ sử dụng hàm liên kết <span class="math inline">\(log()\)</span>. Đối với phân phối biến phụ thuộc, chúng ta có thể chọn giữa phân phối Poisson, phân phối nhị thức âm hoặc phân phối nhị thức do biến tần suất là biến dạng đếm. Hãy nhớ rằng mục tiêu của chúng ta là ước tính tần suất trung bình và mặc dù các giả thiết về phân phối là cần thiết nhưng không quan trọng bằng việc tìm ra các biến độc lập chính xác để đưa vào mô hình.</p>
<p>Nếu phân phối xác suất của số lượng yêu cầu bồi thường là Poisson thì phương sai của biến phụ thuộc phải bằng giá trị trung bình. Tuy nhiên, trong trường hợp dữ liệu chúng ta đang có, và trong hầu hết các tập dữ liệu bảo hiểm, phương sai của tần suất thường lớn hơn giá trị trung bình. Hiện tượng này được gọi là phân tán quá mức. Bạn đọc nên lựa chọn phân phối nhị thức âm trong các trường hợp như vậy. Tuy nhiên, phân phối nhị thức âm không nằm trong nhóm các phân phối kiểu mũ nên để tránh sự phức tạp không cần thiết, chúng tôi vẫn chọn phân phối Poisson cho biến phụ thuộc. Hàm liên kết được sử dụng là hàm log.</p>
<div id="mô-hình-tuyến-tính-tổng-quát-với-một-biến-giải-thích." class="section level3" number="14.3.1">
<h3>
<span class="header-section-number">14.3.1</span> Mô hình tuyến tính tổng quát với một biến giải thích.<a class="anchor" aria-label="anchor" href="#m%C3%B4-h%C3%ACnh-tuy%E1%BA%BFn-t%C3%ADnh-t%E1%BB%95ng-qu%C3%A1t-v%E1%BB%9Bi-m%E1%BB%99t-bi%E1%BA%BFn-gi%E1%BA%A3i-th%C3%ADch."><i class="fas fa-link"></i></a>
</h3>
<p>Mô hình tuyến tính tổng quát đơn giản nhất mà chúng ta có thể áp dụng cho dữ liệu tần suất là mô hình chỉ có duy nhất hệ số chặn. Mô hình này sẽ cho biết tần suất trung bình của biến phụ thuộc. Chúng ta xây dựng mô hình với biến phụ thuộc có phân phối Poisson, với hàm liên kết log, và chỉ có hệ số chặn như sau</p>
<pre><code>## 
## Call:
## glm(formula = clm.count ~ 1, family = poisson(link = "log"), 
##     data = training.dat, offset = log(exposure))
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -0.5720  -0.4953  -0.3692  -0.2335   4.5865  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -1.81050    0.02049  -88.36   &lt;2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 11573  on 28531  degrees of freedom
## Residual deviance: 11573  on 28531  degrees of freedom
## AIC: 16097
## 
## Number of Fisher Scoring iterations: 6</code></pre>
<p>Giá trị ước lượng được của hệ số chặn là <span class="math inline">\(-1.8105\)</span> và giá trị này khác 0 một cách có ý nghĩa thống kê. Mô hình tuyến tính tổng quát trong trường hợp này có thể được viết như sau:
<span class="math display">\[\begin{align}
&amp; Y_i \sim \mathcal{P}(\lambda_i) \\
&amp; \log(\lambda_i) = \log(e_i) + \beta_0
\end{align}\]</span>
trong đó <span class="math inline">\(e_i\)</span> là giá trị của biến <span class="math inline">\(exposure\)</span> của hợp đồng thứ <span class="math inline">\(i\)</span>. Nói cách khác, nếu hợp đồng được quan sát đủ 1 năm (<span class="math inline">\(e_i = 1\)</span>) thì giá trị trung bình của tần suất xảy ra tai nạn là
<span class="math display">\[\begin{align}
\lambda_i = \exp\left(\log(1) + \beta_0\right) = \exp(-1.8105) = 0.164
\end{align}\]</span>
Giá trị này rất gần với giá trị trung bình của biến tần suất mà chúng ta đã tính trong phần phân tích khai phá dữ liệu.</p>
<p>Để xây dựng mô hình có một biến phụ thuộc, chúng ta sẽ sử dụng các tiêu chí để so sánh mô hình được để cập trong chương mô hình tuyến tính tổng quát, bao gồm có thước đo <span class="math inline">\(deviance\)</span> và chỉ tiêu AIC. Nhắc lại rằng thước đo <span class="math inline">\(deviance\)</span> đo khoảng cách từ giá trị log-likelihood của một mô hình tuyến tính tổng quát đến giá trị log-likelihood lớn nhất có thể có được khi sử dụng cùng một phân phối của biến phụ thuộc trong khi AIC là được tính từ giá trị của hàm log-likelihood có điều chỉnh theo số lượng tham số. Mô hình tuyến tính tổng quát có thước đo <span class="math inline">\(deviance\)</span> và chỉ tiêu AIC nhỏ hơn là các mô hình phù hợp hơn với dữ liệu.</p>
<p>Trước khi xây dựng mô hình, bạn đọc cần lưu ý về biến độc lập kiểu số và biến độc lập kiểu factor. Biến <span class="math inline">\(year\)</span> trong mô hình đang được coi là biến kiểu factor với 4 giá trị khác nhau là 2010, 2011, 2012, và 2014, nghĩa là khi chúng ta sử dụng <span class="math inline">\(year\)</span> như một biến độc lập trong mô hình, sẽ có 4 tham số độc lập được ước lượng dành cho biến <span class="math inline">\(year\)</span>, mỗi tham số đại diện cho 1 giá trị. Nếu chúng ta coi biến <span class="math inline">\(year\)</span> như một biến kiểu số, khi xây dựng mô hình sẽ chỉ có một tham số ứng với biến <span class="math inline">\(year\)</span> và thêm 1 hệ số chặn. Với một số biến trong mô hình, chúng ta vừa có thể coi biến đó là kiểu số và vừa có thể coi biến đó là biến kiểu rời rạc. Danh sách các biến nằm trong bảng dưới đây</p>
<div class="inline-table"><table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-15">Bảng 14.6: </span>Các biến vừa có thể là biến kiểu số vừa là rời rạc
</caption>
<thead><tr>
<th style="text-align:right;">
Tên biến
</th>
<th style="text-align:right;">
Số giá trị riêng biệt
</th>
<th style="text-align:right;">
Miền giá trị
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:right;">
yrs.licensed
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
Các số tự nhiên từ 1 đến 9
</td>
</tr>
<tr>
<td style="text-align:right;">
vehicle.age
</td>
<td style="text-align:right;">
19
</td>
<td style="text-align:right;">
Các số tự nhiên từ 0 đến 18
</td>
</tr>
<tr>
<td style="text-align:right;">
prior.claims
</td>
<td style="text-align:right;">
18
</td>
<td style="text-align:right;">
Các số tự nhiên từ 0 đến 20
</td>
</tr>
</tbody>
</table></div>
<p>Đối với các biến này, chúng ta sẽ lưu trong dữ liệu huấn luyện mô hình đồng thời dưới dạng số (tên biến có <span class="math inline">\(.num\)</span> và dưới dạng factor (tên biến có <span class="math inline">\(.f\)</span>).</p>
<div class="sourceCode" id="cb859"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">training.dat</span><span class="op">&lt;-</span><span class="va">training.dat</span><span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>yrs.licensed.num <span class="op">=</span> <span class="va">yrs.licensed</span>,</span>
<span>                                    vehicle.age.num <span class="op">=</span> <span class="va">vehicle.age</span>,</span>
<span>                                    prior.claims.num <span class="op">=</span> <span class="va">prior.claims</span>,</span>
<span>                                    yrs.licensed.f <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="va">yrs.licensed</span><span class="op">)</span>,</span>
<span>                                    vehicle.age.f <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="va">vehicle.age</span><span class="op">)</span>,</span>
<span>                                    prior.claims.f <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="va">prior.claims</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="op">-</span><span class="va">yrs.licensed</span>,<span class="op">-</span><span class="va">vehicle.age</span>,<span class="op">-</span><span class="va">prior.claims</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># thực hiện biến đổi tương tự trên tập xác thực</span></span>
<span><span class="va">test.dat</span><span class="op">&lt;-</span><span class="va">test.dat</span><span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>yrs.licensed.num <span class="op">=</span> <span class="va">yrs.licensed</span>,</span>
<span>                                    vehicle.age.num <span class="op">=</span> <span class="va">vehicle.age</span>,</span>
<span>                                    prior.claims.num <span class="op">=</span> <span class="va">prior.claims</span>,</span>
<span>                                    yrs.licensed.f <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="va">yrs.licensed</span><span class="op">)</span>,</span>
<span>                                    vehicle.age.f <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="va">vehicle.age</span><span class="op">)</span>,</span>
<span>                                    prior.claims.f <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="va">prior.claims</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="op">-</span><span class="va">yrs.licensed</span>,<span class="op">-</span><span class="va">vehicle.age</span>,<span class="op">-</span><span class="va">prior.claims</span><span class="op">)</span></span></code></pre></div>
<p>Chúng ta ước lượng các mô hình GLM với một biến độc lập, tính toán <span class="math inline">\(AIC\)</span> và <span class="math inline">\(deviance\)</span> và mô tả giá trị <span class="math inline">\(deviance\)</span> và <span class="math inline">\(AIC\)</span> trên một đồ thị rải điểm như sau</p>
<div class="sourceCode" id="cb860"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">exposure</span><span class="op">&lt;-</span><span class="va">training.dat</span><span class="op">$</span><span class="va">exposure</span></span>
<span><span class="va">variable.list</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">training.dat</span><span class="op">)</span></span>
<span><span class="va">remove.list</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"pol.id"</span>,<span class="st">"exposure"</span>,<span class="st">"clm.count"</span>,<span class="st">"clm.incurred"</span><span class="op">)</span></span>
<span><span class="va">variable.list</span><span class="op">&lt;-</span><span class="va">variable.list</span><span class="op">[</span><span class="op">!</span><span class="op">(</span><span class="va">variable.list</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="va">remove.list</span><span class="op">)</span><span class="op">]</span></span>
<span><span class="va">deviance</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">variable.list</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">AIC</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">variable.list</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="kw">for</span> <span class="op">(</span><span class="va">i</span> <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">variable.list</span><span class="op">)</span><span class="op">)</span><span class="op">{</span></span>
<span>  <span class="va">x</span> <span class="op">&lt;-</span> <span class="va">variable.list</span><span class="op">[</span><span class="va">i</span><span class="op">]</span></span>
<span>  <span class="va">simple.dat</span><span class="op">&lt;-</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">training.dat</span>,<span class="va">x</span>,<span class="va">clm.count</span><span class="op">)</span></span>
<span>  <span class="va">simple.glm</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">clm.count</span><span class="op">~</span><span class="va">.</span>, family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">poisson</a></span><span class="op">(</span>link <span class="op">=</span> <span class="st">"log"</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">simple.dat</span>,</span>
<span>                  offset <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">exposure</span><span class="op">)</span><span class="op">)</span></span>
<span>  <span class="va">AIC</span><span class="op">[</span><span class="va">i</span><span class="op">]</span><span class="op">&lt;-</span><span class="va">simple.glm</span><span class="op">$</span><span class="va">aic</span></span>
<span>  <span class="va">deviance</span><span class="op">[</span><span class="va">i</span><span class="op">]</span><span class="op">&lt;-</span><span class="va">simple.glm</span><span class="op">$</span><span class="va">deviance</span></span>
<span><span class="op">}</span></span>
<span><span class="va">result</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>variable_names <span class="op">=</span> <span class="va">variable.list</span>, aic <span class="op">=</span> <span class="va">AIC</span>, deviance <span class="op">=</span> <span class="va">deviance</span><span class="op">)</span></span>
<span><span class="va">result</span><span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="op">)</span><span class="op">+</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">AIC</span>, y <span class="op">=</span> <span class="va">deviance</span><span class="op">)</span>, shape <span class="op">=</span> <span class="fl">21</span><span class="op">)</span><span class="op">+</span> </span>
<span>  <span class="fu">geom_label_repel</span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">AIC</span>, y <span class="op">=</span> <span class="va">deviance</span>, label <span class="op">=</span> <span class="va">variable.list</span><span class="op">)</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ggtitle</a></span><span class="op">(</span><span class="st">"So sánh các mô hình GLM có một biến giải thích (1)"</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_minimal</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="10-Ung-dung-GLM_files/figure-html/unnamed-chunk-17-1.png" width="672" style="display: block; margin: auto;"></div>
<p>Đồ thị rải điểm mô tả chỉ tiêu AIC trên trục x và giá trị deviance trên trục y. Các biến giải thích tốt hơn sẽ xuất hiện ở góc dưới bên trái của đồ thị, nơi cả deviance và AIC đều có giá trị nhỏ. Chúng ta thấy các biến <span class="math inline">\(ncd.level\)</span>, <span class="math inline">\(year\)</span> và <span class="math inline">\(yrs.licensed\)</span> là nằm ở góc trái và phía dưới hơn các biến khác. Biến <span class="math inline">\(driver.age\)</span> và <span class="math inline">\(region\)</span> có tác động lên tần suất xảy ra tai nạn nhưng mô hình tuyến tính tổng quát xây dựng trên các biến này lại không có kết quả giống như ta mong muốn. Nguyên nhân là do
- Biến <span class="math inline">\(region\)</span> là biến kiểu rời rạc và có 38 giá trị riêng biệt dẫn đến việc xây dựng mô hình sẽ có quá nhiều tham số.
- Biến <span class="math inline">\(driver.age\)</span> có các giá trị từ 75 tuổi trở lên là có quá ít quan sát và không có tai nạn nào xảy ra.</p>
<p>Đối với các biến kiểu rời rạc trong mô hình tuyến tính tổng quát, kinh nghiệm xây dựng mô hình là kết hợp các nhóm có cùng hệ số ước lượng gần nhau để tạo thành nhóm mới. Điều này giúp mô hình ước lượng có phương sai nhỏ hơn nhưng không làm giảm sai số của mô hình đi quá nhiều. Hình vẽ dưới đây cho biết hệ số ước lượng cho mỗi vùng khác nhau của biến <span class="math inline">\(region\)</span>.</p>
<div class="sourceCode" id="cb861"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">simple.dat</span><span class="op">&lt;-</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">training.dat</span>,<span class="va">region</span>,<span class="va">clm.count</span><span class="op">)</span></span>
<span><span class="va">simple.glm</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">clm.count</span><span class="op">~</span><span class="va">.</span>, family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">poisson</a></span><span class="op">(</span>link <span class="op">=</span> <span class="st">"log"</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">simple.dat</span>,</span>
<span>                  offset <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">exposure</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">dat1</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>d.name <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">simple.glm</span><span class="op">$</span><span class="va">coefficients</span><span class="op">)</span>, coef <span class="op">=</span> <span class="va">simple.glm</span><span class="op">$</span><span class="va">coefficients</span><span class="op">)</span></span>
<span><span class="va">dat1</span><span class="op">$</span><span class="va">d.name</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span><span class="op">&lt;-</span><span class="st">"region1"</span></span>
<span><span class="va">dat1</span><span class="op">$</span><span class="va">coef</span><span class="op">[</span><span class="fl">2</span><span class="op">:</span><span class="fl">38</span><span class="op">]</span><span class="op">&lt;-</span><span class="va">dat1</span><span class="op">$</span><span class="va">coef</span><span class="op">[</span><span class="fl">2</span><span class="op">:</span><span class="fl">38</span><span class="op">]</span><span class="op">+</span><span class="va">dat1</span><span class="op">$</span><span class="va">coef</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span></span>
<span><span class="va">dat1</span><span class="op">&lt;-</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="va">dat1</span>,<span class="op">-</span><span class="va">coef</span><span class="op">)</span></span>
<span><span class="va">dat1</span><span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">coef</span>, y <span class="op">=</span> <span class="va">d.name</span><span class="op">)</span><span class="op">)</span><span class="op">+</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>shape<span class="op">=</span><span class="fl">21</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_discrete.html">scale_y_discrete</a></span><span class="op">(</span>limits <span class="op">=</span> <span class="va">dat1</span><span class="op">$</span><span class="va">d.name</span><span class="op">)</span><span class="op">+</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_minimal</a></span><span class="op">(</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">xlab</a></span><span class="op">(</span><span class="st">""</span><span class="op">)</span><span class="op">+</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ylab</a></span><span class="op">(</span><span class="st">""</span><span class="op">)</span><span class="op">+</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ggtitle</a></span><span class="op">(</span><span class="st">"Hệ số của biến region trong mô hình GLM"</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="10-Ung-dung-GLM_files/figure-html/unnamed-chunk-18-1.png" width="672" style="display: block; margin: auto;"></div>
Chúng ta có thể biến đổi biến <span class="math inline">\(region\)</span> bằng cách nhóm các vùng có hệ số ước lượng tương tự nhau vào cùng nhóm để giảm số lượng tham số.
<div class="inline-table"><table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-19">Bảng 14.7: </span>Nhóm các vùng theo hệ số ước lượng
</caption>
<thead><tr>
<th style="text-align:left;">
Tên biến mới
</th>
<th style="text-align:left;">
Region
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
R1
</td>
<td style="text-align:left;">
7,2
</td>
</tr>
<tr>
<td style="text-align:left;">
R2
</td>
<td style="text-align:left;">
20,22
</td>
</tr>
<tr>
<td style="text-align:left;">
R3
</td>
<td style="text-align:left;">
27,29,14,35
</td>
</tr>
<tr>
<td style="text-align:left;">
R4
</td>
<td style="text-align:left;">
11,37,12,30,28,15,19
</td>
</tr>
<tr>
<td style="text-align:left;">
R5
</td>
<td style="text-align:left;">
4,13,24,3,10,16
</td>
</tr>
<tr>
<td style="text-align:left;">
R6
</td>
<td style="text-align:left;">
1,38,34,31,21,32,25,23
</td>
</tr>
<tr>
<td style="text-align:left;">
R7
</td>
<td style="text-align:left;">
6,33,9,17
</td>
</tr>
<tr>
<td style="text-align:left;">
R8
</td>
<td style="text-align:left;">
8,26
</td>
</tr>
</tbody>
</table></div>
<p>Biến mới được tạo từ biến <span class="math inline">\(region\)</span> được gọi tên là <span class="math inline">\(region.f\)</span> được thêm vào dữ liệu như sau</p>
<div class="sourceCode" id="cb862"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">training.dat</span><span class="op">&lt;-</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span><span class="va">training.dat</span>, region.f <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">region</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">7</span>,<span class="fl">2</span><span class="op">)</span>, <span class="st">"R1"</span>, </span>
<span>                                                     <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">region</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">20</span>,<span class="fl">22</span><span class="op">)</span>, <span class="st">"R2"</span>, </span>
<span>                                                            <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">region</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">27</span>,<span class="fl">29</span>,<span class="fl">14</span>,<span class="fl">35</span><span class="op">)</span>, <span class="st">"R3"</span>,</span>
<span>                                                                   <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">region</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">11</span>,<span class="fl">37</span>,<span class="fl">12</span>,<span class="fl">30</span>,<span class="fl">28</span>,<span class="fl">15</span>,<span class="fl">19</span><span class="op">)</span>, <span class="st">"R4"</span>,</span>
<span>                                                                          <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">region</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">4</span>,<span class="fl">13</span>,<span class="fl">24</span>,<span class="fl">3</span>,<span class="fl">10</span>,<span class="fl">16</span><span class="op">)</span>, <span class="st">"R5"</span>,</span>
<span>                                                                                 <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">region</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">38</span>,<span class="fl">34</span>,<span class="fl">31</span>,<span class="fl">21</span>,<span class="fl">32</span>,<span class="fl">25</span>,<span class="fl">23</span><span class="op">)</span>, <span class="st">"R6"</span>,</span>
<span>                                                                                        <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">region</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">6</span>,<span class="fl">33</span>,<span class="fl">9</span>,<span class="fl">17</span><span class="op">)</span>, <span class="st">"R7"</span>,<span class="st">"R8"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Thực hiện biến đổi tương tự trên tập xác thực</span></span>
<span></span>
<span><span class="va">test.dat</span><span class="op">&lt;-</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span><span class="va">test.dat</span>, region.f <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">region</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">7</span>,<span class="fl">2</span><span class="op">)</span>, <span class="st">"R1"</span>, </span>
<span>                                                     <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">region</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">20</span>,<span class="fl">22</span><span class="op">)</span>, <span class="st">"R2"</span>, </span>
<span>                                                            <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">region</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">27</span>,<span class="fl">29</span>,<span class="fl">14</span>,<span class="fl">35</span><span class="op">)</span>, <span class="st">"R3"</span>,</span>
<span>                                                                   <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">region</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">11</span>,<span class="fl">37</span>,<span class="fl">12</span>,<span class="fl">30</span>,<span class="fl">28</span>,<span class="fl">15</span>,<span class="fl">19</span><span class="op">)</span>, <span class="st">"R4"</span>,</span>
<span>                                                                          <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">region</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">4</span>,<span class="fl">13</span>,<span class="fl">24</span>,<span class="fl">3</span>,<span class="fl">10</span>,<span class="fl">16</span><span class="op">)</span>, <span class="st">"R5"</span>,</span>
<span>                                                                                 <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">region</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">38</span>,<span class="fl">34</span>,<span class="fl">31</span>,<span class="fl">21</span>,<span class="fl">32</span>,<span class="fl">25</span>,<span class="fl">23</span><span class="op">)</span>, <span class="st">"R6"</span>,</span>
<span>                                                                                        <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">region</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">6</span>,<span class="fl">33</span>,<span class="fl">9</span>,<span class="fl">17</span><span class="op">)</span>, <span class="st">"R7"</span>,<span class="st">"R8"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="10-Ung-dung-GLM_files/figure-html/unnamed-chunk-21-1.png" width="672" style="display: block; margin: auto;"></div>
<p>Có thể thấy rằng mô hình với biến <span class="math inline">\(region.f\)</span> có chỉ tiêu AIC nhỏ hơn so với <span class="math inline">\(region\)</span> vì số lượng tham số sử dụng chỉ là 8 tham số thay vì 38 tham số như ban đầu. Bạn đọc có thể tiếp tục quá trình phân tích đơn biến như phân tích đối với biến <span class="math inline">\(region\)</span> để có các biến đầu vào tốt hơn trong mô hình nhiều biến.</p>
<p>Với các phân tích đơn biến ở trên, chúng ta có thể kết luận rằng các biến <span class="math inline">\(ncd.levels\)</span>, <span class="math inline">\(year\)</span>, <span class="math inline">\(nb.rb\)</span>, <span class="math inline">\(region.f\)</span>, <span class="math inline">\(yrs.licenced.f\)</span>, <span class="math inline">\(driver.age\)</span> và <span class="math inline">\(prior.claims\)</span> là các biến có ý nghĩa nhất va có ảnh hưởng đến tần suất gây ra tai nạn. Lưu ý rằng biến <span class="math inline">\(year\)</span> không phải là biến liên quan đến đặc điểm của người lái xe hay phương tiện được bảo hiểm. Trong các mô hình tần suất và mức độ nghiêm trọng, biến thời gian thường được gọi là biến điều khiển và luôn có mặt trong mô hình đa biến.</p>
</div>
</div>
<div id="xây-dựng-mô-hình-tuyến-tính-tổng-quát-nhiều-biến" class="section level2" number="14.4">
<h2>
<span class="header-section-number">14.4</span> Xây dựng mô hình tuyến tính tổng quát nhiều biến<a class="anchor" aria-label="anchor" href="#x%C3%A2y-d%E1%BB%B1ng-m%C3%B4-h%C3%ACnh-tuy%E1%BA%BFn-t%C3%ADnh-t%E1%BB%95ng-qu%C3%A1t-nhi%E1%BB%81u-bi%E1%BA%BFn"><i class="fas fa-link"></i></a>
</h2>
<p>Sau khi đã có ý tưởng tốt hơn về những biến giải thích phù hợp với dữ liệu, chúng ta có thể chuyển sang xây dựng các mô hình kết hợp nhiều hơn một biến giải thích. Về mặt lý thuyết, để tìm ra mô hình đa biến tốt, chúng ta có thể xem xét cả hai mô hình biến và chọn mô hình tốt nhất; sau đó có thể xem xét cả ba mô hình biến và lại chọn mô hình tốt nhất, v.v. Chiến lược này gọi là <span class="math inline">\(forward-stepwise-selection\)</span>. Tuy nhiên với số lượng biến chúng ta hiện có thì chiến lược này không khả thi Một chiến lược khác là xây dựng một mô hình có đầy đủ các biến sau đó lần lượt loại đi các biến không cần thiết. Mặc dù chiến lược này không yêu cầu về mặt tính toán nhưng nhược điểm chính là sự phụ thuộc vào thứ tự chúng ta loại bỏ đi các biến giải thích. Phương pháp khả thi nhất trong trường hợp hày là xây dựng mô hình đa biến được lựa chọn từ một tập hợp con các biến có ý nghĩa trong phân tích một biến sau đó cố gắng thêm các biến khác vào mô hình.</p>
<p>Chúng ta cho mô hình với 7 biến giải thích <span class="math inline">\(ncd.levels\)</span>, <span class="math inline">\(year\)</span>, <span class="math inline">\(nb.rb\)</span>, <span class="math inline">\(region.f\)</span>, <span class="math inline">\(yrs.licenced.f\)</span>, <span class="math inline">\(driver.age\)</span> và <span class="math inline">\(prior.claims.f\)</span> là mô hình cơ sở và sẽ tìm kiếm các biến khác thêm vào mô hình nhằm cải thiện các chỉ tiêu như <span class="math inline">\(deviance\)</span> và <span class="math inline">\(AIC\)</span>.</p>
<div class="inline-figure"><img src="10-Ung-dung-GLM_files/figure-html/unnamed-chunk-22-1.png" width="672" style="display: block; margin: auto;"></div>
<p>Đồ thị trên cho thấy các biến có làm tăng chất lượng của mô hình là <span class="math inline">\(body.code\)</span>, <span class="math inline">\(height\)</span>, và <span class="math inline">\(marital.status\)</span>. Cách tốt nhất để đưa thêm biến độc lập vào mô hình cơ sở là thêm lần lượt từng biến vào mô hình sau đó và lặp lại các bước ở trên. Tuy nhiên, để tránh sự phức tạp không cần thiết, chúng ta sẽ đưa đồng thời cả ba biến vào mô hình sau đó thực hiện kiểm định <span class="math inline">\(\chi^2\)</span>: hiệu số giữa <span class="math inline">\(residual\)</span> <span class="math inline">\(deviance\)</span> của mô hình sau khi thêm biến và mô hình cơ sở có phân phối xấp xỉ phân phối <span class="math inline">\(\chi^2\)</span> với bậc tự do <span class="math inline">\(m_2 - m_1\)</span>, với <span class="math inline">\(m_2 - m_1\)</span> là số lượng tham số thêm vào trong mô hình mới. Biến <span class="math inline">\(body.code\)</span> là biến kiểu factor có 8 giá trị riêng biệt, biết <span class="math inline">\(height\)</span> là biến kiểu số, trong khi biến <span class="math inline">\(marital.status\)</span> là biến kiểu factor có 4 giá trị riêng biệt, do đó thêm 3 biến vào mô hình sẽ làm cho số lượng tham số của mô hình tăng lên là <span class="math inline">\((8-1) + 1 + (4-1) = 11\)</span> tham số.</p>
<div class="inline-table"><table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-23">Bảng 14.8: </span>Thước đo deviance của mô hình cơ sở và mô hình thêm biến
</caption>
<thead><tr>
<th style="text-align:left;">
Mô hình
</th>
<th style="text-align:left;">
Residual Deviance
</th>
<th style="text-align:left;">
Deviance giảm
</th>
<th style="text-align:left;">
Bậc tự do
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
Mô hình cơ sở
</td>
<td style="text-align:left;">
10884.01
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Mô hình thêm biến
</td>
<td style="text-align:left;">
10829.02
</td>
<td style="text-align:left;">
54.99
</td>
<td style="text-align:left;">
11
</td>
</tr>
</tbody>
</table></div>
<p>Giá trị deviance giảm 54.99 sau khi thêm 11 tham số vào mô hình. Lưu ý rằng giá trị phân vị ngưỡng 99.99% của phân phối <span class="math inline">\(\chi^2(11)\)</span> là 37.37, nhỏ hơn 54.99, nên chúng ta có thể kết luận rằng việc thêm 3 biến <span class="math inline">\(body.code\)</span>, <span class="math inline">\(height\)</span>, và <span class="math inline">\(marital.status\)</span> là có ý nghĩa thống kê. Bạn đọc có thể lặp lại các bước ở trên để tìm được thêm các biến có ý nghĩa đưa vào mô hình giải thích tần suất.</p>
</div>
<div id="mô-hình-tuyến-tính-tổng-quát-cho-biến-mức-độ-nghiêm-trọng." class="section level2" number="14.5">
<h2>
<span class="header-section-number">14.5</span> Mô hình tuyến tính tổng quát cho biến mức độ nghiêm trọng.<a class="anchor" aria-label="anchor" href="#m%C3%B4-h%C3%ACnh-tuy%E1%BA%BFn-t%C3%ADnh-t%E1%BB%95ng-qu%C3%A1t-cho-bi%E1%BA%BFn-m%E1%BB%A9c-%C4%91%E1%BB%99-nghi%C3%AAm-tr%E1%BB%8Dng."><i class="fas fa-link"></i></a>
</h2>
<p>Xây dựng mô hình cho mức độ nghiêm trọng khó khăn hơn xây dựng mô hình cho tần suất vì thứ nhất, có ít dữ liệu hơn và thứ hai, các giá trị quan sát được thường biến động lớn. Thông thường, phần lớn các hợp đồng có yêu cầu bồi thường có mức độ nghiêm trọng nhỏ và trong khi một số ít hợp đồng có mức độ nghiêm trọng rất lớn. Điều này thường dẫn đến phân phối của mức độ nghiêm trọng bị lệch phải, như được thể hiện trong biểu đồ ở dưới. Bạn đọc có thể thấy rằng gần như tất cả các quan sát đều tập trung ở phía bên trái của biểu đồ. Có rất ít giá trị lớn hơn 6.000; trên thực tế, chỉ có 11 hợp đồng có yêu cầu bồi thường có mức độ nghiêm trọng lớn hơn 6000 trong tổng số 2209 quan sát có yêu cầu bồi thường trong tập dữ liệu huấn luyện.</p>
<div class="inline-figure"><img src="10-Ung-dung-GLM_files/figure-html/unnamed-chunk-24-1.png" width="672" style="display: block; margin: auto;"></div>
<p>Tương tự như khi xây dựng mô hình cho biến tần suất, chúng ta bắt đầu xây dựng mô hình cho biến mức độ nghiêm trọng bằng mô hình không có biến phụ thuộc.</p>
<div class="sourceCode" id="cb863"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">clm.serverity</span> <span class="op">~</span><span class="fl">1</span>, family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">Gamma</a></span><span class="op">(</span>link <span class="op">=</span> <span class="st">"log"</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">training.dat</span>, weights <span class="op">=</span> <span class="va">clm.count</span> , subset <span class="op">=</span> <span class="va">clm.count</span><span class="op">&gt;</span><span class="fl">0</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Call:  glm(formula = clm.serverity ~ 1, family = Gamma(link = "log"), 
##     data = training.dat, weights = clm.count, subset = clm.count &gt; 
##         0)
## 
## Coefficients:
## (Intercept)  
##       6.685  
## 
## Degrees of Freedom: 2208 Total (i.e. Null);  2208 Residual
## Null Deviance:       4626 
## Residual Deviance: 4626  AIC: 36280</code></pre>
<p>Mô hình không có biến giải thích có hệ số chặn là 6.685, nghĩa là giá trị trung bình của biến mức độ nghiêm trọng là <span class="math inline">\(e^{6.685} = 800.31\)</span> tương tự như giá trị trung bình đã tính toán ở phần khai phá dữ liệu.</p>
<p>Biến <span class="math inline">\(year\)</span> kiểm soát tác động của thời gian lên mức độ nghiêm trọng, do đó chúng ta sẽ đưa biến này vào tất cả các mô hình cho mức độ nghiêm trọng. Các bước để xây dựng mô hình giống như khi chúng ta xây dựng mô hình cho tần suất: chúng ta cần tìm kiếm các biến giải thích (ngoài biến <span class="math inline">\(year\)</span>) có khả năng dự đoán mức độ nghiêm trọng của các yêu cầu bồi thường. Quá trình này tương tự như phần trước nên chúng tôi sẽ cố gắng trình bày ngắn gọn nhất có thể.</p>
<div id="mô-hình-đơn-biến-cho-mức-độ-nghiêm-trọng" class="section level3" number="14.5.1">
<h3>
<span class="header-section-number">14.5.1</span> Mô hình đơn biến cho mức độ nghiêm trọng<a class="anchor" aria-label="anchor" href="#m%C3%B4-h%C3%ACnh-%C4%91%C6%A1n-bi%E1%BA%BFn-cho-m%E1%BB%A9c-%C4%91%E1%BB%99-nghi%C3%AAm-tr%E1%BB%8Dng"><i class="fas fa-link"></i></a>
</h3>
<p>Mô hình đơn biến được hiểu là mô hình bao gồm hệ số chặn, biến điều khiển <span class="math inline">\(year\)</span> và một biến giải thích. Tương tự như khi xây dựng mô hình cho biến tần suất, chúng ta tính toán <span class="math inline">\(deviance\)</span> và chỉ tiêu <span class="math inline">\(AIC\)</span> cho các mô hình và biểu diễn kết quả trên một đồ thị rải điểm</p>
<div class="sourceCode" id="cb865"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">variable.list</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">training.dat</span><span class="op">)</span></span>
<span><span class="va">remove.list</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"pol.id"</span>,<span class="st">"exposure"</span>,<span class="st">"clm.count"</span>,<span class="st">"clm.incurred"</span>,<span class="st">"clm.serverity"</span>, <span class="st">"year"</span>, <span class="st">"region"</span><span class="op">)</span></span>
<span><span class="va">variable.list</span><span class="op">&lt;-</span><span class="va">variable.list</span><span class="op">[</span><span class="op">!</span><span class="op">(</span><span class="va">variable.list</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="va">remove.list</span><span class="op">)</span><span class="op">]</span></span>
<span><span class="va">p</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">variable.list</span><span class="op">)</span></span>
<span><span class="va">v.clm.count</span><span class="op">&lt;-</span><span class="va">training.dat</span><span class="op">$</span><span class="va">clm.count</span></span>
<span><span class="va">deviance</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">0</span>,<span class="va">p</span><span class="op">+</span><span class="fl">1</span><span class="op">)</span></span>
<span><span class="va">AIC</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">0</span>,<span class="va">p</span><span class="op">+</span><span class="fl">1</span><span class="op">)</span></span>
<span><span class="kw">for</span> <span class="op">(</span><span class="va">i</span> <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="va">p</span><span class="op">)</span><span class="op">{</span></span>
<span>  <span class="va">x</span> <span class="op">&lt;-</span> <span class="va">variable.list</span><span class="op">[</span><span class="va">i</span><span class="op">]</span></span>
<span>  <span class="va">simple.dat</span><span class="op">&lt;-</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">training.dat</span>,<span class="va">year</span>,<span class="va">x</span>,<span class="va">clm.serverity</span><span class="op">)</span></span>
<span>  <span class="va">simple.glm</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">clm.serverity</span><span class="op">~</span><span class="va">.</span>, family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">Gamma</a></span><span class="op">(</span>link <span class="op">=</span> <span class="st">"log"</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">simple.dat</span>, weights <span class="op">=</span> <span class="va">v.clm.count</span>, subset <span class="op">=</span> <span class="va">v.clm.count</span><span class="op">&gt;</span><span class="fl">0</span><span class="op">)</span></span>
<span>  <span class="va">AIC</span><span class="op">[</span><span class="va">i</span><span class="op">]</span><span class="op">&lt;-</span><span class="va">simple.glm</span><span class="op">$</span><span class="va">aic</span></span>
<span>  <span class="va">deviance</span><span class="op">[</span><span class="va">i</span><span class="op">]</span><span class="op">&lt;-</span><span class="va">simple.glm</span><span class="op">$</span><span class="va">deviance</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="va">simple.dat</span><span class="op">&lt;-</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">training.dat</span>,<span class="va">year</span>,<span class="va">clm.serverity</span><span class="op">)</span></span>
<span><span class="va">simple.glm</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">clm.serverity</span><span class="op">~</span><span class="va">.</span>, family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">Gamma</a></span><span class="op">(</span>link <span class="op">=</span> <span class="st">"log"</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">simple.dat</span>, weights <span class="op">=</span> <span class="va">v.clm.count</span>, subset <span class="op">=</span> <span class="va">v.clm.count</span><span class="op">&gt;</span><span class="fl">0</span><span class="op">)</span></span>
<span><span class="va">AIC</span><span class="op">[</span><span class="va">p</span><span class="op">+</span><span class="fl">1</span><span class="op">]</span><span class="op">&lt;-</span><span class="va">simple.glm</span><span class="op">$</span><span class="va">aic</span></span>
<span><span class="va">deviance</span><span class="op">[</span><span class="va">p</span><span class="op">+</span><span class="fl">1</span><span class="op">]</span><span class="op">&lt;-</span><span class="va">simple.glm</span><span class="op">$</span><span class="va">deviance</span></span>
<span></span>
<span><span class="va">result</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>variable_names <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">variable.list</span>,<span class="st">"Null"</span><span class="op">)</span>, aic <span class="op">=</span> <span class="va">AIC</span>, deviance <span class="op">=</span> <span class="va">deviance</span>, last.col <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">0</span>,<span class="va">p</span><span class="op">)</span>,<span class="fl">1</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">result</span><span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="op">)</span><span class="op">+</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">AIC</span>, y <span class="op">=</span> <span class="va">deviance</span>,, size <span class="op">=</span> <span class="va">last.col</span>, fill <span class="op">=</span> <span class="va">last.col</span><span class="op">)</span>, shape <span class="op">=</span> <span class="fl">21</span><span class="op">)</span><span class="op">+</span> </span>
<span>  <span class="fu">geom_label_repel</span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">AIC</span>, y <span class="op">=</span> <span class="va">deviance</span>, label <span class="op">=</span> <span class="va">variable_names</span><span class="op">)</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ggtitle</a></span><span class="op">(</span><span class="st">"Mô hình GLM đơn biến cho mức độ nghiêm trọng"</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_fill_manual</a></span><span class="op">(</span>values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"white"</span>,<span class="st">"black"</span><span class="op">)</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_size_manual</a></span><span class="op">(</span>values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>,<span class="fl">3</span><span class="op">)</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_minimal</a></span><span class="op">(</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>legend.position <span class="op">=</span> <span class="st">"none"</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="10-Ung-dung-GLM_files/figure-html/unnamed-chunk-26-1.png" width="672" style="display: block; margin: auto;"></div>
<p>Mô hình “Null” là mô hình chỉ bao gồm biến <span class="math inline">\(year\)</span> và hệ số chặn. Có thể thấy rằng việc thêm biến giải thích vào mô hình sẽ làm cho <span class="math inline">\(deviance\)</span> giảm, nhưng chưa chắc chỉ số AIC sẽ giảm vì AIC tính đến số lượng tham số trong mô hình. Một số biến có làm giảm AIC của mô hình bao gồm có <span class="math inline">\(ncd.level\)</span>, <span class="math inline">\(nb.rb\)</span>, <span class="math inline">\(marital.status\)</span>, <span class="math inline">\(yrs.licensed.num\)</span>, <span class="math inline">\(driver.gender\)</span>.</p>
</div>
<div id="mô-hình-nhiều-biến-cho-mức-độ-nghiêm-trọng" class="section level3" number="14.5.2">
<h3>
<span class="header-section-number">14.5.2</span> Mô hình nhiều biến cho mức độ nghiêm trọng<a class="anchor" aria-label="anchor" href="#m%C3%B4-h%C3%ACnh-nhi%E1%BB%81u-bi%E1%BA%BFn-cho-m%E1%BB%A9c-%C4%91%E1%BB%99-nghi%C3%AAm-tr%E1%BB%8Dng"><i class="fas fa-link"></i></a>
</h3>
<p>Chúng ta xây dựng mô hình đa biến bao gồm 5 biến kể trên sau đó tìm kiếm thêm các biến khác.</p>
<div class="sourceCode" id="cb866"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">glm1</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">clm.serverity</span> <span class="op">~</span> <span class="va">year</span> <span class="op">+</span> <span class="va">ncd.level</span><span class="op">+</span> <span class="va">nb.rb</span> <span class="op">+</span> <span class="va">marital.status</span> <span class="op">+</span> <span class="va">yrs.licensed.num</span> <span class="op">+</span> <span class="va">driver.gender</span>, </span>
<span>         family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">Gamma</a></span><span class="op">(</span>link <span class="op">=</span> <span class="st">"log"</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">training.dat</span>, weights <span class="op">=</span> <span class="va">clm.count</span>, subset <span class="op">=</span> <span class="va">clm.count</span><span class="op">&gt;</span><span class="fl">0</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">glm1</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = clm.serverity ~ year + ncd.level + nb.rb + marital.status + 
##     yrs.licensed.num + driver.gender, family = Gamma(link = "log"), 
##     data = training.dat, weights = clm.count, subset = clm.count &gt; 
##         0)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -3.9662  -1.5961  -0.6651   0.3050   3.7805  
## 
## Coefficients:
##                        Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)            6.628362   0.227028  29.196   &lt;2e-16 ***
## year2011              -0.232547   0.106311  -2.187   0.0288 *  
## year2012               0.128161   0.092530   1.385   0.1662    
## year2013               0.271938   0.094109   2.890   0.0039 ** 
## ncd.level2            -0.237103   0.268439  -0.883   0.3772    
## ncd.level3             0.007723   0.073769   0.105   0.9166    
## ncd.level4            -0.123855   0.102547  -1.208   0.2273    
## ncd.level5            -0.215120   0.125589  -1.713   0.0869 .  
## ncd.level6            -0.196879   0.114226  -1.724   0.0849 .  
## nb.rbRB               -0.086679   0.075003  -1.156   0.2479    
## marital.statusMarried  0.102740   0.204406   0.503   0.6153    
## marital.statusSingle   0.204259   0.241585   0.845   0.3979    
## marital.statusWidow    0.428399   0.283793   1.510   0.1313    
## yrs.licensed.num       0.002306   0.021181   0.109   0.9133    
## driver.genderMale     -0.128635   0.086560  -1.486   0.1374    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for Gamma family taken to be 1.854572)
## 
##     Null deviance: 4626.1  on 2208  degrees of freedom
## Residual deviance: 4526.6  on 2194  degrees of freedom
## AIC: 36243
## 
## Number of Fisher Scoring iterations: 8</code></pre>
<p>Có thể thấy rằng biến <span class="math inline">\(yrs.licensed.num\)</span> có thể làm giảm AIC trong mô hình đơn biến nhưng trong mô hình đa biến biến này lại không có ý nghĩa. Chúng ta sẽ loại bỏ biến <span class="math inline">\(yrs.licensed.num\)</span> ra khỏi mô hình đa biến. Các biến khác đều là các biến dạng factor và không phải tất cả các giá trị của biến factor đều có ý nghĩa thống kê. Chẳng hạn như <span class="math inline">\(ncd.level3\)</span> gần như không có khác biệt với <span class="math inline">\(ncd.level1\)</span>. Hoặc các giá trị <span class="math inline">\(Divorced\)</span> và <span class="math inline">\(Married\)</span> của biến <span class="math inline">\(marital.status\)</span> cũng không có sự khác biệt. Điều này gợi ý cho bạn đọc về việc tạo các biến <span class="math inline">\(ncd.level\)</span> và <span class="math inline">\(marital.status\)</span> mới có ý nghĩa thống kê hơn. Trong phần này của cuốn sách, để tránh sự phức tạp không cần thiết, chúng tôi sẽ giữ nguyên các biến <span class="math inline">\(ncd.level\)</span> và <span class="math inline">\(marital.status\)</span> ở trạng thái hiện tại.</p>
<p>Chúng ta coi mô hình bao gồm 5 biến giải thích <span class="math inline">\(year\)</span>, <span class="math inline">\(ncd.level\)</span>, <span class="math inline">\(nb.rb\)</span>, <span class="math inline">\(marital.status\)</span>, và <span class="math inline">\(driver.gender\)</span> là mô hình cơ sở để tìm kiếm thêm các biến giải thích khác.</p>
<div class="inline-figure"><img src="10-Ung-dung-GLM_files/figure-html/unnamed-chunk-28-1.png" width="672" style="display: block; margin: auto;"></div>
<p>Đồ thị trên gợi ý cho chúng ta biết biến <span class="math inline">\(vehicle.age.num\)</span> là một biến giải thích tốt có làm giảm chỉ tiêu AIC. Chúng ta thực hiện kiểm định <span class="math inline">\(\chi^2\)</span> để kiểm tra xem việc thêm biến vào có ý nghĩa thống kê hay không</p>
<div class="inline-table"><table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-29">Bảng 14.9: </span>Thước đo deviance của mô hình cơ sở và mô hình thêm biến
</caption>
<thead><tr>
<th style="text-align:left;">
Mô hình
</th>
<th style="text-align:left;">
Residual Deviance
</th>
<th style="text-align:left;">
Deviance giảm
</th>
<th style="text-align:left;">
Bậc tự do
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
Mô hình cơ sở
</td>
<td style="text-align:left;">
4526.664
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Mô hình thêm biến
</td>
<td style="text-align:left;">
4519.061
</td>
<td style="text-align:left;">
7.6
</td>
<td style="text-align:left;">
1
</td>
</tr>
</tbody>
</table></div>
<p>Giá trị deviance giảm 7.6 sau khi thêm 1 tham số vào mô hình. Đây là giá trị phân vị ngưỡng 99.4% của phân phối <span class="math inline">\(\chi^2(1)\)</span> nên chúng ta có thể kết luận rằng việc thêm biến <span class="math inline">\(vehicle.age.num\)</span> là có ý nghĩa thống kê. Bạn đọc có thể lặp lại các bước ở trên để tìm được thêm các biến có ý nghĩa đưa vào mô hình giải thích mức độ nghiêm trọng.</p>
</div>
</div>
<div id="xác-định-phí-bảo-hiểm-thuần-và-xác-thực-mô-hình" class="section level2" number="14.6">
<h2>
<span class="header-section-number">14.6</span> Xác định phí bảo hiểm thuần và xác thực mô hình<a class="anchor" aria-label="anchor" href="#x%C3%A1c-%C4%91%E1%BB%8Bnh-ph%C3%AD-b%E1%BA%A3o-hi%E1%BB%83m-thu%E1%BA%A7n-v%C3%A0-x%C3%A1c-th%E1%BB%B1c-m%C3%B4-h%C3%ACnh"><i class="fas fa-link"></i></a>
</h2>
<p>Trong phần này, chúng ta kết hợp các mô hình tần suất và mức độ nghiêm trọng để xác định mức phí bảo hiểm thuần. Công thức xác định phí bảo hiểm thuần chỉ đơn giản là
<span class="math display">\[\begin{align}
\textit{Phí bảo hiểm thuần} = \textit{Tần suất} \times \textit{Mức độ nghiêm trọng}
\end{align}\]</span></p>
<p>Chúng ta sử dụng mô hình tần suất và mô hình mức độ nghiêm trọng với các biến được xác định trong phần trước. Danh sách các biến được liệt kê trong bảng dưới đây.</p>
<div class="inline-table"><table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-30">Bảng 14.10: </span>Các biến sử dụng trong xác định phí bảo hiểm thuần
</caption>
<thead><tr>
<th style="text-align:left;">
Mô hình
</th>
<th style="text-align:left;">
Danh sách biến
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
Tần suất
</td>
<td style="text-align:left;">
year, ncd.level, nb.rb, yrs.licensed.f, region.f, driver.age, prior.claims.f,body.code, height, marital.status
</td>
</tr>
<tr>
<td style="text-align:left;">
Mức độ nghiêm trọng
</td>
<td style="text-align:left;">
year, ncd.level, nb.rb, marital.status, driver.gender, vehicle.age.num
</td>
</tr>
</tbody>
</table></div>
<p>Chúng ta thêm biến tần suất trung bình (<span class="math inline">\(E.fre\)</span>), mức độ nghiêm trọng trung bình (<span class="math inline">\(E.ser\)</span>) và phí thuần (<span class="math inline">\(Net.prem\)</span>) vào dữ liệu huấn luyện mô hình.</p>
<div class="sourceCode" id="cb868"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">glm.fre</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">clm.count</span><span class="op">~</span> <span class="va">year</span> <span class="op">+</span> <span class="va">ncd.level</span><span class="op">+</span> <span class="va">nb.rb</span><span class="op">+</span> <span class="va">yrs.licensed.f</span> <span class="op">+</span> <span class="va">region.f</span> <span class="op">+</span> <span class="va">driver.age</span> <span class="op">+</span> </span>
<span>               <span class="va">prior.claims.f</span> <span class="op">+</span> <span class="va">marital.status</span> <span class="op">+</span>  <span class="va">body.code</span><span class="op">+</span> <span class="va">height</span>, </span>
<span>             family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">poisson</a></span><span class="op">(</span>link <span class="op">=</span> <span class="st">"log"</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">training.dat</span>,</span>
<span>                offset <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">exposure</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">glm.ser</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">clm.serverity</span> <span class="op">~</span> <span class="va">year</span> <span class="op">+</span> <span class="va">ncd.level</span><span class="op">+</span> <span class="va">nb.rb</span> <span class="op">+</span> <span class="va">marital.status</span> <span class="op">+</span> <span class="va">driver.gender</span> <span class="op">+</span> <span class="va">vehicle.age.num</span>, </span>
<span>         family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">Gamma</a></span><span class="op">(</span>link <span class="op">=</span> <span class="st">"log"</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">training.dat</span>, weights <span class="op">=</span> <span class="va">clm.count</span>, subset <span class="op">=</span> <span class="va">clm.count</span><span class="op">&gt;</span><span class="fl">0</span><span class="op">)</span></span>
<span></span>
<span><span class="co">## Tính toán expected frequency và expected severity</span></span>
<span><span class="va">training.dat</span><span class="op">&lt;-</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span><span class="va">training.dat</span>, E.fre <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">glm.fre</span>, <span class="va">training.dat</span><span class="op">)</span><span class="op">)</span>,</span>
<span>                     E.ser <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">glm.ser</span>, <span class="va">training.dat</span><span class="op">)</span><span class="op">)</span>,</span>
<span>                     Net.prem <span class="op">=</span> <span class="va">E.fre</span><span class="op">*</span><span class="va">E.ser</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Dự đoán expected frequency và expected severity trên test</span></span>
<span><span class="va">test.dat</span><span class="op">&lt;-</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span><span class="va">test.dat</span>, E.fre <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">glm.fre</span>, <span class="va">test.dat</span><span class="op">)</span><span class="op">)</span>,</span>
<span>                     E.ser <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">glm.ser</span>, <span class="va">test.dat</span><span class="op">)</span><span class="op">)</span>,</span>
<span>                 Net.prem <span class="op">=</span> <span class="va">E.fre</span> <span class="op">*</span> <span class="va">E.ser</span><span class="op">)</span></span></code></pre></div>
<p>Chúng ta thực hiện so sánh giữa tổng phí thuần của tất cả các hợp đồng với tổng số tiền thực trả cho các hợp đồng trong tập dữ liệu huấn luyện. Không có gì ngạc nhiên khi tổng tần suất trung bình bằng tổng số yêu cầu bổi thường và tổng phí bảo hiểm thuần xấp xỉ tổng số tiền yêu cầu bồi thường thực tế do mô hình được xây dựng trên tập huấn luyện.</p>
<div class="inline-table"><table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-32">Bảng 14.11: </span>Giá trị thực tế và dự đoán trên dữ liệu huấn luyên mô hình
</caption>
<thead><tr>
<th style="text-align:center;">
</th>
<th style="text-align:center;">
Thực tế
</th>
<th style="text-align:center;">
Dự đoán
</th>
<th style="text-align:center;">
Tỷ lệ dự đoán/thực tế
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:center;">
Tần suất yêu cầu bồi thường
</td>
<td style="text-align:center;">
2382
</td>
<td style="text-align:center;">
2382
</td>
<td style="text-align:center;">
100%
</td>
</tr>
<tr>
<td style="text-align:center;">
Tổng chi phí bồi thường
</td>
<td style="text-align:center;">
1906958
</td>
<td style="text-align:center;">
1914962
</td>
<td style="text-align:center;">
100.42%
</td>
</tr>
</tbody>
</table></div>
<p>Thước đo quan trọng nhất về hiệu quả của mô hình là khả năng dự đoán của mô hình trên tập dữ liệu được sử dụng để kiểm tra (<span class="math inline">\(test.dat\)</span>). Tổng số lượng yêu cầu bồi thường và tổng chi phí bồi thường được dự đoán bằng mô hình tần suất - mức độ nghiêm trọng được so sánh với giá trị thực tế như ở bảng dưới đây</p>
<div class="inline-table"><table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-33">Bảng 14.12: </span>Giá trị thực tế và dự đoán trên dữ liệu huấn luyên mô hình
</caption>
<thead><tr>
<th style="text-align:center;">
</th>
<th style="text-align:center;">
Thực tế
</th>
<th style="text-align:center;">
Dự đoán
</th>
<th style="text-align:center;">
Tỷ lệ dự đoán/thực tế
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:center;">
Tần suất yêu cầu bồi thường
</td>
<td style="text-align:center;">
1049.0
</td>
<td style="text-align:center;">
1004.69
</td>
<td style="text-align:center;">
95.78%
</td>
</tr>
<tr>
<td style="text-align:center;">
Tổng chi phí bồi thường
</td>
<td style="text-align:center;">
804228.5
</td>
<td style="text-align:center;">
807962.62
</td>
<td style="text-align:center;">
100.46%
</td>
</tr>
</tbody>
</table></div>
<p>Bạn đọc có thể thấy rằng trên dữ liệu ngoài mẫu, tổng số lượng yêu cầu bồi thường dự đoán bằng 95.78% tổng số lượng yêu cầu bồi thường thực tế, trong khi tổng số tiền yêu cầu bồi thường dự đoán bằng 100.46% tổng số tiền yêu cầu bồi thường thực tế. Có thể thấy rằng khả năng dự đoán ngoài mẫu của mô hình về cơ bản không thể giống như dự đoán trong mẫu, tuy nhiên các tỷ lệ 95.78% và 100.46% là vượt quá mức độ kỳ vọng vì tổng số lượng hợp đồng ngoài mẫu là 12228 hợp đồng.</p>
<p>Ngoài phương pháp xác thực bằng dữ liệu ngoài mẫu, bạn đọc cũng có thể sử dụng xác thực chéo để đánh giá khả năng dự đoán của mô hình. Chúng ta sẽ chia dữ liệu ban đầu thành 5 phần (một cách ngẫu nhiên), tạm gọi là các phần 1, 2, 3, 4 và 5. Mỗi lần xây dựng mô hình, chúng ta sẽ lấy 1 phần làm dữ liệu ngoài mẫu và sử dụng 4 phần còn lại để xây dựng mô hình. Một mô hình ổn định là mô hình có khả năng dự đoán trên các tập ngoài mẫu không bị biến động quá nhiều.</p>
</div>
<div id="kết-luận" class="section level2" number="14.7">
<h2>
<span class="header-section-number">14.7</span> Kết luận<a class="anchor" aria-label="anchor" href="#k%E1%BA%BFt-lu%E1%BA%ADn"><i class="fas fa-link"></i></a>
</h2>
<p>Chúng ta đã thảo luận về một số bước cần thiết để phát triển một mô hình xác định phí bảo hiểm thuần, yếu tố quan trọng nhất trong quá trình hình thành phí bảo hiểm. Đê thực các bước này, chúng ta đã thực hiện một số phân tích dữ liệu khám phá để làm quen với dữ liệu và nhằm đạt được một số hiểu biết quan trọng trong giai đoạn lập mô hình. Tiếp theo chúng tôi bắt đầu vào việc tạo ra một số mô hình tuyến tính tổng quát cho biến tần suất yêu cầu bồi thường và biến mức độ nghiêm trọng của yêu cầu bồi thường. Các biến được sử dụng trong mô hình bao gồm cả các biến liên tục và biến rời rạc. Một vài biến được chuyển đổi để tăng khả năng giải thích các biến mục tiêu. Sau cùng, chúng tôi kết hợp hai mô hình lại để xác định phí bảo hiểm thuần. Mô hình được xác thực trên một tập dữ liệu ngoài mẫu và cho kết quả rất khả quan.</p>
<p>Nhìn chung, chúng ta đã hoàn thành khá nhiều bước để tiến đến kết quả. Tuy nhiên trong thực tế, để đưa phí thuần vào hoạt động kinh doanh vẫn còn nhiều việc phải làm. Các bước tiếp theo vượt quá phạm vi của mô hình toán thông thường nên sẽ không nằm trong phạm vi của cuốn sách này.</p>
<!-- # REFERENCE -->
<!-- ### Source from thesis -->
<!-- **1.** Chen, Chun-houh, Wolfgang Karl Härdle, and Antony Unwin, eds (2007). *Handbook of data visualization.* \ -->
<!-- **2.** Aparicio, Manuela, and Carlos J. Costa. (2015). *Data visualization - Communication design quarterly review.* \ -->
<!-- **3.** Hadley Wickham. (2010). *A Layered Grammar of Graphics.* \ -->
<!-- ### Souce from website -->
<!-- **4.** [https://www.tableau.com/learn/articles/data-visualization](https://www.tableau.com/learn/articles/data-visualization) \ -->
<!-- **5.** [https://www.r-graph-gallery.com/ggplot2-package.html](https://www.r-graph-gallery.com/ggplot2-package.html) \ -->
<!-- **6.** [http://r-statistics.co/ggplot2-Tutorial-With-R.html](http://r-statistics.co/ggplot2-Tutorial-With-R.html) \ -->
<!-- **7.** [https://www.maths.usyd.edu.au/u/UG/SM/STAT3022/r/current/Misc/data-visualization-2.1.pdf](https://www.maths.usyd.edu.au/u/UG/SM/STAT3022/r/current/Misc/data-visualization-2.1.pdf) \ -->
<!-- **8.** [https://www.kaggle.com/](https://www.kaggle.com/) \ -->

<pre><code>## 
## Attaching package: 'dplyr'</code></pre>
<pre><code>## The following objects are masked from 'package:stats':
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union</code></pre>
<pre><code>## 
## Attaching package: 'kableExtra'</code></pre>
<pre><code>## The following object is masked from 'package:dplyr':
## 
##     group_rows</code></pre>
<pre><code>## 
## Attaching package: 'gridExtra'</code></pre>
<pre><code>## The following object is masked from 'package:dplyr':
## 
##     combine</code></pre>
<pre><code>## 
## Attaching package: 'pryr'</code></pre>
<pre><code>## The following object is masked from 'package:dplyr':
## 
##     where</code></pre>
<pre><code>## Loading required package: lattice</code></pre>
<pre><code>## Loading required package: splines</code></pre>
<pre><code>## Loading required package: foreach</code></pre>
<pre><code>## Loaded gam 1.22-3</code></pre>
<pre><code>## randomForest 4.7-1.1</code></pre>
<pre><code>## Type rfNews() to see new features/changes/bug fixes.</code></pre>
<pre><code>## 
## Attaching package: 'randomForest'</code></pre>
<pre><code>## The following object is masked from 'package:gridExtra':
## 
##     combine</code></pre>
<pre><code>## The following object is masked from 'package:ggplot2':
## 
##     margin</code></pre>
<pre><code>## The following object is masked from 'package:dplyr':
## 
##     combine</code></pre>
</div>
</div>



  <div class="chapter-nav">
<div class="prev"><a href="m%C3%B4-h%C3%ACnh-t%E1%BA%A7n-su%E1%BA%A5t---m%E1%BB%A9c-%C4%91%E1%BB%99-nghi%C3%AAm-tr%E1%BB%8Dng..html"><span class="header-section-number">13</span> Mô hình tần suất - mức độ nghiêm trọng.</a></div>
<div class="next"><a href="m%C3%B4-h%C3%ACnh-c%C3%A2y-quy%E1%BA%BFt-%C4%91%E1%BB%8Bnh.html"><span class="header-section-number">15</span> Mô hình cây quyết định</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#t%C3%ADnh-to%C3%A1n-ph%C3%AD-b%E1%BA%A3o-hi%E1%BB%83m-thu%E1%BA%A7n-b%E1%BA%B1ng-m%C3%B4-h%C3%ACnh-t%E1%BA%A7n-su%E1%BA%A5t---m%E1%BB%A9c-%C4%91%E1%BB%99-nghi%C3%AAm-tr%E1%BB%8Dng."><span class="header-section-number">14</span> Tính toán phí bảo hiểm thuần bằng mô hình tần suất - mức độ nghiêm trọng.</a></li>
<li><a class="nav-link" href="#d%E1%BB%AF-li%E1%BB%87u-%C4%91%E1%BB%83-x%C3%A2y-d%E1%BB%B1ng-m%C3%B4-h%C3%ACnh"><span class="header-section-number">14.1</span> Dữ liệu để xây dựng mô hình</a></li>
<li>
<a class="nav-link" href="#ph%C3%A2n-t%C3%ADch-khai-ph%C3%A1-d%E1%BB%AF-li%E1%BB%87u"><span class="header-section-number">14.2</span> Phân tích khai phá dữ liệu</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#bi%E1%BA%BFn-t%E1%BA%A7n-su%E1%BA%A5t-v%C3%A0-m%E1%BB%91i-li%C3%AAn-h%E1%BB%87-%C4%91%E1%BA%BFn-c%C3%A1c-bi%E1%BA%BFn-kh%C3%A1c"><span class="header-section-number">14.2.1</span> Biến tần suất và mối liên hệ đến các biến khác</a></li>
<li><a class="nav-link" href="#bi%E1%BA%BFn-m%E1%BB%A9c-%C4%91%E1%BB%99-nghi%C3%AAm-tr%E1%BB%8Dng-v%C3%A0-m%E1%BB%91i-li%C3%AAn-h%E1%BB%87-v%E1%BB%9Bi-c%C3%A1c-bi%E1%BA%BFn-kh%C3%A1c"><span class="header-section-number">14.2.2</span> Biến mức độ nghiêm trọng và mối liên hệ với các biến khác</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#m%C3%B4-h%C3%ACnh-tuy%E1%BA%BFn-t%C3%ADnh-t%E1%BB%95ng-qu%C3%A1t-cho-t%E1%BA%A7n-su%E1%BA%A5t."><span class="header-section-number">14.3</span> Mô hình tuyến tính tổng quát cho tần suất.</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#m%C3%B4-h%C3%ACnh-tuy%E1%BA%BFn-t%C3%ADnh-t%E1%BB%95ng-qu%C3%A1t-v%E1%BB%9Bi-m%E1%BB%99t-bi%E1%BA%BFn-gi%E1%BA%A3i-th%C3%ADch."><span class="header-section-number">14.3.1</span> Mô hình tuyến tính tổng quát với một biến giải thích.</a></li></ul>
</li>
<li><a class="nav-link" href="#x%C3%A2y-d%E1%BB%B1ng-m%C3%B4-h%C3%ACnh-tuy%E1%BA%BFn-t%C3%ADnh-t%E1%BB%95ng-qu%C3%A1t-nhi%E1%BB%81u-bi%E1%BA%BFn"><span class="header-section-number">14.4</span> Xây dựng mô hình tuyến tính tổng quát nhiều biến</a></li>
<li>
<a class="nav-link" href="#m%C3%B4-h%C3%ACnh-tuy%E1%BA%BFn-t%C3%ADnh-t%E1%BB%95ng-qu%C3%A1t-cho-bi%E1%BA%BFn-m%E1%BB%A9c-%C4%91%E1%BB%99-nghi%C3%AAm-tr%E1%BB%8Dng."><span class="header-section-number">14.5</span> Mô hình tuyến tính tổng quát cho biến mức độ nghiêm trọng.</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#m%C3%B4-h%C3%ACnh-%C4%91%C6%A1n-bi%E1%BA%BFn-cho-m%E1%BB%A9c-%C4%91%E1%BB%99-nghi%C3%AAm-tr%E1%BB%8Dng"><span class="header-section-number">14.5.1</span> Mô hình đơn biến cho mức độ nghiêm trọng</a></li>
<li><a class="nav-link" href="#m%C3%B4-h%C3%ACnh-nhi%E1%BB%81u-bi%E1%BA%BFn-cho-m%E1%BB%A9c-%C4%91%E1%BB%99-nghi%C3%AAm-tr%E1%BB%8Dng"><span class="header-section-number">14.5.2</span> Mô hình nhiều biến cho mức độ nghiêm trọng</a></li>
</ul>
</li>
<li><a class="nav-link" href="#x%C3%A1c-%C4%91%E1%BB%8Bnh-ph%C3%AD-b%E1%BA%A3o-hi%E1%BB%83m-thu%E1%BA%A7n-v%C3%A0-x%C3%A1c-th%E1%BB%B1c-m%C3%B4-h%C3%ACnh"><span class="header-section-number">14.6</span> Xác định phí bảo hiểm thuần và xác thực mô hình</a></li>
<li><a class="nav-link" href="#k%E1%BA%BFt-lu%E1%BA%ADn"><span class="header-section-number">14.7</span> Kết luận</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/NEUKhoaToanKT/Khoa_hoc_du_lieu_trong_KTKD/blob/master/10-Ung-dung-GLM.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/NEUKhoaToanKT/Khoa_hoc_du_lieu_trong_KTKD/edit/master/10-Ung-dung-GLM.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Khoa Học Dữ Liệu trong Kinh tế và Kinh doanh</strong>" was written by Nguyễn Quang Huy. It was last built on 2024-08-05.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
